/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2016-10-06 11:30:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.surveyManager.editQuestions;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ilu.surveytool.databasemanager.DataObject.Resource;
import java.util.List;
import ilu.surveytool.databasemanager.constants.DBConstants;
import ilu.surveytool.constants.Attribute;
import ilu.surveytool.databasemanager.DataObject.Question;
import ilu.surveytool.language.Language;

public final class eQuestionBodyContent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ilu.surveytool.language.Language");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.constants.DBConstants");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.Resource");
    _jspx_imports_classes.add("ilu.surveytool.constants.Attribute");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.Question");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

Question question = (Question) request.getAttribute(Attribute.s_QUESTION);
//String title = question.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_TITLE).getText();

Language lang = new Language(getServletContext().getRealPath("/")); 
lang.loadLanguage(Language.getLanguageRequest(request));

String descriptionText = "";
if(question.getContents().containsKey(DBConstants.s_VALUE_CONTENTTYPE_NAME_DESCRIPTION))
{
	descriptionText = question.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_DESCRIPTION).getText(); 
}

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tplaceholderBContent = \"");
      out.print( lang.getContent("placeholder.type_here") );
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<li class=\"panel-question\" id=\"panel-question1\" qid=\"");
      out.print( question.getQuestionId() );
      out.write("\" index=\"");
      out.print( question.getIndex() );
      out.write("\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "eqComponents/eqHeadBodyContent.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<div class=\"panel-body\">\r\n");
      out.write("\t\t<div class=\"question-frame\">\r\n");
      out.write("\t\t<h6>");
      out.print(lang.getContent("question.edit.statementSetting.title"));
      out.write("</h6>\t\t\t\t\t\t\t\t\t\r\n");
      out.write(" \t\t<div class=\"container\">\r\n");
      out.write("  \t\t\t<div class=\"rowPlus\">\r\n");
      out.write("  \r\n");
      out.write("    \t\t<label>");
      out.print( lang.getContent("bcontent.statement") );
      out.write("</label>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<div class=\"btn-toolbar\" data-role=\"editor-");
      out.print(question.getQuestionId());
      out.write("-toolbar\" data-target=\"#editor-");
      out.print(question.getQuestionId());
      out.write("\">\r\n");
      out.write("      \t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("        \t\t\t\t<a class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\" title=\"");
      out.print( lang.getContent("bcontent.font"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.font"));
      out.write("\"><i class=\"fa fa-font\"></i><b class=\"caret\"></b></a>\r\n");
      out.write("          \t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Serif\" title=\"Serif\" data-original-title=\"Serif\" style=\"font-family:'Serif'\">Serif</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Sans\" title=\"Sans\" data-original-title=\"Sans\" style=\"font-family:'Sans'\">Sans</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Arial\" title=\"Arial\" data-original-title=\"Arial\" style=\"font-family:'Arial'\">Arial</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Arial Black\" title=\"Arial Black\" data-original-title=\"Arial Black\" style=\"font-family:'Arial Black'\">Arial Black</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Courier\" title=\"Courier\" data-original-title=\"Courier\" style=\"font-family:'Courier'\">Courier</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Courier New\" title=\"Courier New\" data-original-title=\"Courier New\" style=\"font-family:'Courier New'\">Courier New</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Comic Sans MS\" title=\"Comic Sans MS\" data-original-title=\"Comic Sans MS\" style=\"font-family:'Comic Sans MS'\">Comic Sans MS</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Helvetica\" title=\"Helvetica\" data-original-title=\"Helvetica\" style=\"font-family:'Helvetica'\">Helvetica</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Impact\" title=\"Impact\" data-original-title=\"Impact\" style=\"font-family:'Impact'\">Impact</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Lucida Grande\" title=\"Lucida Grande\" data-original-title=\"Lucida Grande\" style=\"font-family:'Lucida Grande'\">Lucida Grande</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Lucida Sans\" title=\"Lucida Sans\" data-original-title=\"Lucida Sans\" style=\"font-family:'Lucida Sans'\">Lucida Sans</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Tahoma\" title=\"Tahoma\" data-original-title=\"Tahoma\" style=\"font-family:'Tahoma'\">Tahoma</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Times\" title=\"Times\" data-original-title=\"Times\" style=\"font-family:'Times'\">Times</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Times New Roman\" title=\"Times New Roman\" data-original-title=\"Times New Roman\" style=\"font-family:'Times New Roman'\">Times New Roman</a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontName Verdana\" title=\"Verdana\" data-original-title=\"Verdana\" style=\"font-family:'Verdana'\">Verdana</a></li>\r\n");
      out.write("          \t\t\t\t</ul>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("      \t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("        \t\t\t\t<a class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\" title=\"");
      out.print( lang.getContent("bcontent.font.size"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.font.size"));
      out.write("\"><i class=\"fa fa-text-height\"></i><b class=\"caret\"></b></a>\r\n");
      out.write("          \t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontSize 5\" title=\"");
      out.print( lang.getContent("bcontent.huge"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.huge"));
      out.write("\"><font size=\"5\">");
      out.print( lang.getContent("bcontent.huge"));
      out.write("</font></a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontSize 3\" title=\"");
      out.print( lang.getContent("bcontent.normal"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.normal"));
      out.write("\"><font size=\"3\">");
      out.print( lang.getContent("bcontent.normal"));
      out.write("</font></a></li>\r\n");
      out.write("          \t\t\t\t\t<li><a data-edit=\"fontSize 1\" title=\"");
      out.print( lang.getContent("bcontent.small"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.small"));
      out.write("\"><font size=\"1\">");
      out.print( lang.getContent("bcontent.small"));
      out.write("</font></a></li>\r\n");
      out.write("          \t\t\t\t</ul>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("      \t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("        \t\t\t\t<a class=\"btn btn-primary\" data-edit=\"bold\" title=\"");
      out.print( lang.getContent("bcontent.bold"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.bold"));
      out.write("\"><i class=\"fa fa-bold\"></i></a>\r\n");
      out.write("        \t\t\t\t<a class=\"btn btn-primary\" data-edit=\"italic\" title=\"");
      out.print( lang.getContent("bcontent.italic"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.italic"));
      out.write("\"><i class=\"fa fa-italic\"></i></a>\r\n");
      out.write("        \t\t\t\t<a class=\"btn btn-primary\" data-edit=\"strikethrough\" title=\"");
      out.print( lang.getContent("bcontent.strikethrough"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.strikethrough"));
      out.write("\"><i class=\"fa fa-strikethrough\"></i></a>\r\n");
      out.write("        \t\t\t\t<a class=\"btn btn-primary\" data-edit=\"underline\" title=\"");
      out.print( lang.getContent("bcontent.underline"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.underline"));
      out.write("\"><i class=\"fa fa-underline\"></i></a>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("      \t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t        <a class=\"btn btn-primary\" data-edit=\"insertunorderedlist\" title=\"");
      out.print( lang.getContent("bcontent.bullet"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.bullet"));
      out.write("\"><i class=\"fa fa-list\"></i></a>\r\n");
      out.write("\t\t\t\t        <a class=\"btn btn-primary\" data-edit=\"insertorderedlist\" title=\"");
      out.print( lang.getContent("bcontent.number"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.number"));
      out.write("\"><i class=\"fa fa-list-ol\"></i></a>\r\n");
      out.write("\t\t\t\t        <a class=\"btn btn-primary\" data-edit=\"outdent\" title=\"");
      out.print( lang.getContent("bcontent.reduce"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.reduce"));
      out.write("\"><i class=\"fa fa-outdent\"></i></a>\r\n");
      out.write("\t\t\t\t        <a class=\"btn btn-primary\" data-edit=\"indent\" title=\"");
      out.print( lang.getContent("bcontent.indent"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.indent"));
      out.write("\"><i class=\"fa fa-indent\"></i></a>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("      \t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("        \t\t\t\t<a class=\"btn btn-primary\" data-edit=\"justifyleft\" title=\"");
      out.print( lang.getContent("bcontent.left"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.left"));
      out.write("\"><i class=\"fa fa-align-left\"></i></a>\r\n");
      out.write("\t\t\t\t        <a class=\"btn btn-primary\" data-edit=\"justifycenter\" title=\"");
      out.print( lang.getContent("bcontent.center"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.center"));
      out.write("\"><i class=\"fa fa-align-center\"></i></a>\r\n");
      out.write("\t\t\t\t        <a class=\"btn btn-primary\" data-edit=\"justifyright\" title=\"");
      out.print( lang.getContent("bcontent.right"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.right"));
      out.write("\"><i class=\"fa fa-align-right\"></i></a>\r\n");
      out.write("\t\t\t\t        <a class=\"btn btn-primary\" data-edit=\"justifyfull\" title=\"");
      out.print( lang.getContent("bcontent.justify"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.justify"));
      out.write("\"><i class=\"fa fa-align-justify\"></i></a>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("      \t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("      \t\t\t\t\t<a class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\" title=\"");
      out.print( lang.getContent("bcontent.hyperlink"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.hyperlink"));
      out.write("\"><i class=\"fa fa-link\"></i></a>\r\n");
      out.write("        \t\t\t\t<div class=\"dropdown-menu input-append\">\r\n");
      out.write("          \t\t\t\t\t<input class=\"form-control form-edit\" placeholder=\"URL\" type=\"text\" data-edit=\"createLink\">\r\n");
      out.write("          \t\t\t\t\t<button class=\"btn btn-primary btn-add-link\" type=\"button\">");
      out.print( lang.getContent("bcontent.add"));
      out.write("</button>\r\n");
      out.write("        \t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t<a class=\"btn btn-primary\" data-edit=\"unlink\" title=\"");
      out.print( lang.getContent("bcontent.remove"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.remove"));
      out.write("\"><i class=\"fa fa-unlink\"></i></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t        <a class=\"btn btn-primary\" data-edit=\"undo\" title=\"");
      out.print( lang.getContent("bcontent.undo"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.undo"));
      out.write("\"><i class=\"fa fa-undo\"></i></a>\r\n");
      out.write("\t\t\t\t        <a class=\"btn btn-primary\" data-edit=\"redo\" title=\"");
      out.print( lang.getContent("bcontent.redo"));
      out.write("\" data-original-title=\"");
      out.print( lang.getContent("bcontent.redo"));
      out.write("\"><i class=\"fa fa-repeat\"></i></a>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t\r\n");
      out.write("\t\t    \t<!-- <label for=\"editor-");
      out.print(question.getQuestionId());
      out.write("\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.bcontent") );
      out.write("</label> -->\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<button class=\"btn visuallyhidden\" id=\"accesibilityHelp\" aria-label=\"");
      out.print( lang.getContent("button.accesibility_help") );
      out.write("\"></button>\r\n");
      out.write("\t\t\t\t<div id=\"editor-");
      out.print(question.getQuestionId());
      out.write("\" class=\"wellBContent col-md-9 editor\" contenteditable=\"true\">");
if(descriptionText.equals("")){
      out.print(lang.getContent("placeholder.type_here"));
}else{
      out.print( descriptionText );
}
      out.write("</div>\r\n");
      out.write("\t\t    <script>\r\n");
      out.write("\t\t    $.getScript('http://mindmup.github.io/bootstrap-wysiwyg/external/jquery.hotkeys.js',function(){\r\n");
      out.write("\t\t    \t$.getScript('http://mindmup.github.io/bootstrap-wysiwyg/bootstrap-wysiwyg.js',function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t    \t  $('#");
      out.print("editor-"+question.getQuestionId());
      out.write("').wysiwyg({ toolbarSelector: '[data-role=");
      out.print("editor-"+question.getQuestionId());
      out.write("-toolbar]'} );\r\n");
      out.write("\t\t    \t  $('#");
      out.print("editor-"+question.getQuestionId());
      out.write("').cleanHtml();\r\n");
      out.write("\r\n");
      out.write("\t\t    \t});\r\n");
      out.write("\t\t    \t});\r\n");
      out.write("\t\t    </script>\r\n");
      out.write("\t\t    \r\n");
      out.write("  \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "eqComponents/eqFiles.jsp", out, false);
      out.write("\r\n");
      out.write(" \t\t</div>\r\n");
      out.write("\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("</li>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
