/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2016-10-06 11:33:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.surveyManager.editQuestions.eqComponents;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ilu.surveytool.constants.Parameter;
import org.codehaus.jettison.json.JSONObject;
import org.codehaus.jettison.json.JSONArray;
import ilu.surveytool.databasemanager.DataObject.Option;
import ilu.surveytool.databasemanager.constants.DBConstants;
import ilu.surveytool.databasemanager.DataObject.LogicGoTo;
import ilu.surveytool.databasemanager.DataObject.Resource;
import ilu.surveytool.databasemanager.DataObject.QDependence;
import ilu.surveytool.databasemanager.DataObject.QDependenceValue;
import java.util.List;
import ilu.surveytool.language.Language;
import ilu.surveytool.databasemanager.constants.DBConstants;
import ilu.surveytool.constants.Attribute;
import ilu.surveytool.databasemanager.DataObject.Question;

public final class eqDependences_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.Option");
    _jspx_imports_classes.add("org.codehaus.jettison.json.JSONObject");
    _jspx_imports_classes.add("org.codehaus.jettison.json.JSONArray");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.Question");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.QDependence");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ilu.surveytool.constants.Parameter");
    _jspx_imports_classes.add("ilu.surveytool.language.Language");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.constants.DBConstants");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.QDependenceValue");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.Resource");
    _jspx_imports_classes.add("ilu.surveytool.constants.Attribute");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.LogicGoTo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

												Language lang = new Language(getServletContext().getRealPath("/")); 
												lang.loadLanguage(Language.getLanguageRequest(request));
												
												Question question = (Question) request.getAttribute(Attribute.s_QUESTION);
												String title = "";
			    								if(question!=null &&  question.getContents()!=null && question.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_TITLE)!=null){
			    									title = question.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_TITLE).getText();
			    								}
												QDependence qdependence = question.getQDependence();
												
												boolean withLogic = Boolean.parseBoolean(request.getParameter("withLogic"));
												
												int numPage = (int) request.getAttribute(Attribute.s_NUM_PAGE);
												JSONArray pagesJson = (JSONArray) request.getAttribute(Attribute.s_JSON_PAGES);
							  					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t<div class=\"question-frame\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t<h6>");
      out.print( lang.getContent("question.edit.dependences.title") );
      out.write("</h6>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t<div class=\"dependences-frame\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t");

															if(qdependence==null){
															
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t<button class=\"btn-transparent btn-close-aspa btn-close-dependences hidden\"><span class=\"visuallyhidden\">");
      out.print( lang.getContent("button.close.dependences") );
      out.write("</span><i class=\"fa fa-times-circle fa-2x\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t<div class=\"dependences-button center\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm active\">");
      out.print( lang.getContent("button.add_dependence") );
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t<div class=\"dependences-settings hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<ul class=\"dependences-list form-inline\" index = \"0\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "eqDependenceItem.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("index", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("hidden", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("true", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "eqDependenceItem.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( title ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("index", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("-1", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("hidden", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("false", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<div class=\"dependences-add-button center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm active\">");
      out.print( lang.getContent("button.add_dependence") );
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t");

															}
															else{
																
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn-transparent btn-close-aspa btn-close-dependences hidden\"><span class=\"visuallyhidden\">");
      out.print( lang.getContent("button.close.dependences") );
      out.write("</span><i class=\"fa fa-times-circle fa-2x\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t<div class=\"dependences-settings\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dependences-list form-inline\" index = \"");
      out.print( qdependence.getId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "eqDependenceItem.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("index", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("hidden", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("true", request.getCharacterEncoding()), out, false);
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

																int i=1;
																for (QDependenceValue depval : qdependence.getqdepval()){
																	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"dependence-item\" index=\"");
      out.print( depval.getItemId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");

																	if(i==1){
																		
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<fieldset id=\"fieldset-dependence\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<legend class=\"visuallyhidden\">");
      out.print( i );
      out.write('º');
      out.write(' ');
      out.print( lang.getContent("question.edit.dependence.legend") + " "+ title);
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<label for=\"dependence-condition-");
      out.print( i );
      out.write("\" class=\"dependence-condition-label visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.condition.label") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<div class=\"form-group\"  style=\"margin:0px !important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<select id=\"dependence-condition-");
      out.print( i );
      out.write("\" class=\"form-control dependence-condition hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t");
if(qdependence.getDependenceType().equals(DBConstants.s_VALUE_DEPENDENCETYPE_AND)){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write("\" selected>");
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write('"');
      out.write('>');
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write("\" selected>");
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"dependence-question-");
      out.print( i );
      out.write("\" class=\"dependence-question-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.question.label_hidden") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
      out.print( lang.getContent("question.edit.dependence.question.label_shown") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">(");
      out.print( lang.getContent("question.edit.dependence.question.label_help_hidden") );
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<label for=\"dependence-question-");
      out.print( i );
      out.write("\" class=\"next-dependence-question-label hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.question.label_hidden") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
      out.print( lang.getContent("question.edit.dependence.question.label_next_shown") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">(");
      out.print( lang.getContent("question.edit.dependence.question.label_help_hidden") );
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t");

																	}
																	else if(i==2){
																		
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<fieldset id=\"fieldset-dependence\" class=\"fieldset-second-dependence\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<legend class=\"visuallyhidden\">");
      out.print( i );
      out.write('º');
      out.write(' ');
      out.print( lang.getContent("question.edit.dependence.legend") + " "+ title);
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"dependence-condition-");
      out.print( i );
      out.write("\" class=\"dependence-condition-label visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.condition.label") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<div class=\"form-group\"  style=\"margin:0px !important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<select id=\"dependence-condition-");
      out.print( i );
      out.write("\" class=\"form-control dependence-condition\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
if(qdependence.getDependenceType().equals(DBConstants.s_VALUE_DEPENDENCETYPE_AND)){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write("\" selected>");
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write('"');
      out.write('>');
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write("\" selected>");
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<label for=\"dependence-question-");
      out.print( i );
      out.write("\" class=\"dependence-question-label hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.question.label_hidden") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
      out.print( lang.getContent("question.edit.dependence.question.label_shown") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">(");
      out.print( lang.getContent("question.edit.dependence.question.label_help_hidden") );
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<label for=\"dependence-question-");
      out.print( i );
      out.write("\" class=\"next-dependence-question-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.question.label_hidden") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
      out.print( lang.getContent("question.edit.dependence.question.label_next_shown") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">(");
      out.print( lang.getContent("question.edit.dependence.question.label_help_hidden") );
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

																	}
																	else{
																		
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<fieldset id=\"fieldset-dependence\" class=\"fieldset-next-dependences\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<legend class=\"visuallyhidden\">");
      out.print( i );
      out.write('º');
      out.write(' ');
      out.print( lang.getContent("question.edit.dependence.legend") + " "+ title);
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<label for=\"dependence-condition-");
      out.print( i );
      out.write("\" class=\"dependence-condition-label visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.condition.label") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<div class=\"form-group\"  style=\"margin:0px !important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<select id=\"dependence-condition-");
      out.print( i );
      out.write("\" class=\"form-control dependence-condition hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t");
if(qdependence.getDependenceType().equals(DBConstants.s_VALUE_DEPENDENCETYPE_AND)){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write("\" selected>");
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write('"');
      out.write('>');
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write("\" selected>");
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<label for=\"dependence-question-");
      out.print( i );
      out.write("\" class=\"dependence-question-label hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.question.label_hidden") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
      out.print( lang.getContent("question.edit.dependence.question.label_shown") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">(");
      out.print( lang.getContent("question.edit.dependence.question.label_help_hidden") );
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"dependence-question-");
      out.print( i );
      out.write("\" class=\"next-dependence-question-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.question.label_hidden") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
      out.print( lang.getContent("question.edit.dependence.question.label_next_shown") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">(");
      out.print( lang.getContent("question.edit.dependence.question.label_help_hidden") );
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

																	}
																	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\"  style=\"margin:0px !important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"dependence-question-");
      out.print( i );
      out.write("\" class=\"form-control dependence-question\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"none\" class=\"default-option\">");
      out.print( lang.getContent("question.edit.dependence.question.label_help_hidden") );
      out.write("</option>\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option id=\"question-dependence-");
      out.print( depval.getPid() + "-" + depval.getQid() );
      out.write("\" value=\"");
      out.print( depval.getPid() + "-" + depval.getQid() );
      out.write("\" selected> ");
      out.print( depval.getQName());
      out.write(" </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<label for=\"dependence-option-");
      out.print( i );
      out.write("\" class=\"dependence-option-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.option.label_hidden") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
      out.print( lang.getContent("question.edit.dependence.option.label_shown") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">(");
      out.print( lang.getContent("question.edit.dependence.option.label_help_hidden") );
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<div class=\"form-group\"  style=\"margin:0px !important;\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"dependence-option-");
      out.print( i );
      out.write("\" class=\"form-control dependence-option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"none\" class=\"default-option\">");
      out.print( lang.getContent("question.edit.dependence.option.label_help_hidden") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option id=\"option-dependence-");
      out.print( depval.getOgid() + "-" + depval.getOid() );
      out.write("\" value=\"");
      out.print( depval.getOgid() + "-" + depval.getOid() );
      out.write("\" selected> ");
      out.print( depval.getOName());
      out.write(" </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id='dependence-option-feedback' class='glyphicon glyphicon-remove form-control-feedback hidden' aria-hidden='true' style='top:0px;right: 10px'></span>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id='dependence-option-error' class='error hidden' style='top:0px;left: 160px'>");
      out.print( lang.getContent("msg.error.dependence-option.text") );
      out.write("</span>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<div class=\"option-icons fright\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<label for=\"remove-dependence\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.remove.dependence") );
      out.write(' ');
      out.write(' ');
      out.print( i );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fright red trash\" id=\"remove-dependence\" aria-label=\"");
      out.print( lang.getContent("button.remove_dependence") );
      out.write(' ');
      out.print( i );
      out.write("\"><i class=\"fa fa-trash fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

																	i++;
																}
																
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<div class=\"dependences-add-button center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm active\">");
      out.print( lang.getContent("button.add_dependence") );
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t");
	
															}
															
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t");
 if(withLogic) 
							  						   {							  								
							  						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t<div class=\"logic-frame\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t");

							  							if(!question.getOptionsGroups().isEmpty())
					  									{
							  							
							  									
							  										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<button class=\"btn-transparent btn-close-aspa btn-close-logic hidden\"><span class=\"visuallyhidden\">");
      out.print( lang.getContent("button.close.logic") );
      out.write("</span><i class=\"fa fa-times-circle fa-2x\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<div class=\"logic-button center\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm active\">");
      out.print( lang.getContent("button.add_logic") );
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t<div class=\"logic-settings hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<ul class=\"logic-option-list form-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");

							  										for(Option option : question.getOptionsGroups().get(0).getOptions())
							  										{
							  											LogicGoTo logicGoTo = null;
							  											if(!question.getLogicGoTo().isEmpty())
							  											{
							  												for(LogicGoTo lgt : question.getLogicGoTo())
									  										{
							  													if(option.getId() == lgt.getOid()) logicGoTo = lgt;
									  										}
							  											}
							  									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<li class=\"logic-option\"  ogid=\"");
      out.print( question.getOptionsGroups().get(0).getId());
      out.write("\" oid=\"");
      out.print( option.getId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<label for=\"logic-option-goto-");
      out.print( option.getId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( lang.getContent("question.edit.logic.option.label") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"form-control\" id=\"logic-option-");
      out.print( option.getId() );
      out.write('"');
      out.write('>');
      out.print( option.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_TITLE).getText() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( lang.getContent("question.edit.logic.option.goto.label") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<select id=\"logic-option-goto-");
      out.print( option.getId() );
      out.write("\" class=\"form-control logic-option-goto\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");

							  													if(logicGoTo == null)
							  													{
							  									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"none\" class=\"default-option\" selected>");
      out.print( lang.getContent("question.edit.logic.option.goto.continue") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");

							  													}
							  													else
							  													{
							  									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"none\" class=\"default-option\">");
      out.print( lang.getContent("question.edit.logic.option.goto.continue") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t\t<option  id=\"option-goto-");
      out.print( logicGoTo.getQDestId() );
      out.write("\" value=\"");
      out.print( logicGoTo.getQDestId() );
      out.write("\" selected>");
      out.print( logicGoTo.getQDest() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");
					
							  													}
							  									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");

								  									}
										  									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");

					  									}
					  									else
					  									{
					  									
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<button class=\"btn-transparent btn-close-aspa btn-close-logic hidden\"><span class=\"visuallyhidden\">");
      out.print( lang.getContent("button.close.logic") );
      out.write("</span><i class=\"fa fa-times-circle fa-2x\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"logic-settings hidden\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<p>");
      out.print( lang.getContent("question.edit.logic.no_option") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"logic-button center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm active\">");
      out.print( lang.getContent("button.add_logic") );
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");
	
					  									}					  									
							  							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t</div>\t\t\t\t\t\t  \t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

												lang.close();
												
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
