/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2016-10-06 11:33:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.surveyManager.editQuestions.eqComponents;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ilu.surveytool.constants.Parameter;
import ilu.surveytool.language.Language;

public final class eqDependenceItem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ilu.surveytool.constants.Parameter");
    _jspx_imports_classes.add("ilu.surveytool.language.Language");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

																Language lang = new Language(getServletContext().getRealPath("/")); 
																lang.loadLanguage(Language.getLanguageRequest(request));
																
																String title = request.getParameter(Parameter.s_TITLE);
																String index = request.getParameter(Parameter.s_INDEX);
																boolean hidden = Boolean.parseBoolean(request.getParameter("hidden"));
																
																if(hidden)
																{
																
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<li class=\"dependence-item hidden\" index=\"");
      out.print( index );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");

																}else{
																
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"dependence-item\" index=\"");
      out.print( index );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
	
																}
							  									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<fieldset id=\"fieldset-dependence\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<legend class=\"visuallyhidden\">");
      out.print( index );
      out.write('º');
      out.write(' ');
      out.print( lang.getContent("question.edit.dependence.legend") );
      out.write(' ');
      out.print( title );
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<!--<label for=\"dependence-action-");
      out.print( index );
      out.write("\" class=\"dependence-action-label visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.action.label") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<select id=\"dependence-action-");
      out.print( index );
      out.write("\" class=\"form-control dependence-action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<option value=\"show\" selected>");
      out.print( lang.getContent("question.edit.dependence.action.option.show") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<option value=\"hide\" >");
      out.print( lang.getContent("question.edit.dependence.action.option.hide") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</select>-->\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<label for=\"dependence-condition-");
      out.print( index );
      out.write("\" class=\"dependence-condition-label visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.condition.label") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<div class=\"form-group\"  style=\"margin:0px !important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<select id=\"dependence-condition-");
      out.print( index );
      out.write("\" class=\"form-control dependence-condition hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write("\" selected>");
      out.print( lang.getContent("question.edit.dependence.condition.option.and") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print( lang.getContent("question.edit.dependence.condition.option.or") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<label for=\"dependence-question-");
      out.print( index );
      out.write("\" class=\"dependence-question-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.question.label_hidden") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
      out.print( lang.getContent("question.edit.dependence.question.label_shown") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">(");
      out.print( lang.getContent("question.edit.dependence.question.label_help_hidden") );
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<label for=\"dependence-question-");
      out.print( index );
      out.write("\" class=\"next-dependence-question-label hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.question.label_hidden") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
      out.print( lang.getContent("question.edit.dependence.question.label_next_shown") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">(");
      out.print( lang.getContent("question.edit.dependence.question.label_help_hidden") );
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<div class=\"form-group\"  style=\"margin:0px !important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<select id=\"dependence-question-");
      out.print( index );
      out.write("\" class=\"form-control dependence-question\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<option value=\"none\" class=\"default-option\" selected>");
      out.print( lang.getContent("question.edit.dependence.question.label_help_hidden") );
      out.write("</option>\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<label for=\"dependence-option-");
      out.print( index );
      out.write("\" class=\"dependence-option-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">");
      out.print( lang.getContent("question.edit.dependence.option.label_hidden") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t");
      out.print( lang.getContent("question.edit.dependence.option.label_shown") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span class=\"visuallyhidden\">(");
      out.print( lang.getContent("question.edit.dependence.option.label_help_hidden") );
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<div class=\"form-group\"  style=\"margin:0px !important;\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"dependence-option-");
      out.print( index );
      out.write("\" class=\"form-control dependence-option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<option value=\"none\" class=\"default-option\" selected>");
      out.print( lang.getContent("question.edit.dependence.option.label_help_hidden") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id='dependence-option-feedback' class='glyphicon glyphicon-remove form-control-feedback hidden' aria-hidden='true' style='top:0px;right: 10px'></span>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id='dependence-option-error' class='error hidden' style='top:0px;left: 160px'>");
      out.print( lang.getContent("msg.error.dependence-option.text") );
      out.write("</span>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<div class=\"option-icons fright\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<label for=\"remove-dependence\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.remove.dependence") );
      out.write(' ');
      out.write(' ');
      out.print( index );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fright red trash\" id=\"remove-dependence\" aria-label=\"");
      out.print( lang.getContent("button.remove_dependence") );
      out.write(' ');
      out.print( index );
      out.write("\"><i class=\"fa fa-trash fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t</li>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
