/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2016-10-06 11:27:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.surveyManager.frames;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ilu.surveytool.constants.Address;
import ilu.surveytool.language.Language;

public final class fNewPoll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ilu.surveytool.constants.Address");
    _jspx_imports_classes.add("ilu.surveytool.language.Language");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

Language lang = new Language(getServletContext().getRealPath("/")); 
lang.loadLanguage(Language.getLanguageRequest(request));

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t  \t\t\t<!-- Modal -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"modal fade survey-win\" id=\"newPollModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-dialog poll-win-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t    \t<div class=\"panel panel-primary\"> \r\n");
      out.write("\t\t\t\t    \t\t<div class=\"panel-heading\"> \r\n");
      out.write("\t\t\t\t        \t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"");
      out.print( lang.getContent("button.close") );
      out.write("\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("\t\t\t\t    \t\t\t<h2 class=\"panel-title\">");
      out.print( lang.getContent("poll.new.title") );
      out.write("</h2> \r\n");
      out.write("\t\t\t\t    \t\t</div> \r\n");
      out.write("\t\t\t\t    \t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t    \t\t\t\t<form method=\"POST\" id=\"newPollForm\" class=\"form-horizontal\">\r\n");
      out.write("\t\t\t    \t\t\t\t\t<fieldset class=\"survey-frame\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t<legend>");
      out.print( lang.getContent("poll.new.legend.info") );
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-7 margin-bottom-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pollTitle\" class=\"col-sm-2 control-label left\">");
      out.print( lang.getContent("poll.new.label.poll_title") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     \t\t<div class=\"form-group\" style=\"margin:0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     \t\t\t<input type=\"text\" class=\"form-control\" id=\"pollTitle\" name=\"title\" placeholder=\"");
      out.print( lang.getContent("poll.new.placeholder.poll_title") );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     \t\t\t<span  id='pollTitle-feedback' class='glyphicon glyphicon-remove form-control-feedback hidden' aria-hidden='true'></span>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span id='pollTitle-error' class='error hidden' style='top: 0px;'>");
      out.print( lang.getContent("msg.error.poll.title") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pollProject\" class=\"col-sm-3 control-label left\"> ");
      out.print( lang.getContent("poll.new.label.project") );
      out.write(" </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t\t<div class=\"form-group\" style=\"margin:0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t\t\t<input type=\"text\" class=\"form-control\" id=\"pollProject\" name=\"project\" placeholder=\"");
      out.print( lang.getContent("poll.new.placeholder.project") );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t\t\t<span  id='pollProject-feedback' class='glyphicon glyphicon-remove form-control-feedback hidden' aria-hidden='true'></span>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span id='pollProject-error' class='error hidden' style='top: 0px;'>");
      out.print( lang.getContent("msg.error.poll.project") );
      out.write("</span>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<fieldset class=\"survey-frame\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t<legend>");
      out.print( lang.getContent("poll.new.legend.question") );
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"margin-bottom-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin:0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"qstatement\" >");
      out.print( lang.getContent("question.statement") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t     \t\t<textarea class=\"form-control\" id=\"qstatement\" rows=\"3\" placeholder=\"");
      out.print( lang.getContent("placeholder.type_here") );
      out.write("\"></textarea>\t\t\t\t\t\t\t\t\t     \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span  id='qstatement-feedback' class='glyphicon glyphicon-remove form-control-feedback hidden' aria-hidden='true' style='top:30px;right: 20px'></span>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t<span id='qstatement-error' class='error hidden' style=''>");
      out.print( lang.getContent("msg.error.qstatement.text") );
      out.write("</span>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t     \t\t<legend>");
      out.print( lang.getContent("question.edit.legend.options") );
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t     \t\t<ul class=\"option-list\" id=\"option-list\" otype=\"radio\">\t\t\t\t\t\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t<li class=\"option-item\" id=\"option-item\">\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-transparent fleft\"><i class=\"fa fa-sort fa-2x\"></i></button> -->\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"circle-info circle-grey fleft\">1</div>\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin:0px;\">\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id='option1' class=\"form-control fleft\" index=\"1\" placeholder=\"");
      out.print( lang.getContent("question.edit.placeholder.option") );
      out.write(" 1\" aria-label=\"");
      out.print( lang.getContent("question.edit.aria_label.option") );
      out.write(" 1\" style=\"width: 100%; !important;\"/>\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span  id='option1-feedback' class='glyphicon glyphicon-remove form-control-feedback hidden' aria-hidden='true' style=\"color:#A94442;right: 20px;\"></span>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<span  id='option1-error' class='error hidden' style='top: 0px;right: -180px;'>");
      out.print( lang.getContent("msg.error.poll.option") );
      out.write("</span>\t\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"option-icons fleft\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-transparent fleft\" data-toggle=\"modal\" data-target=\"#importFile\"><i class=\"fa fa-file-image-o fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft\"><i class=\"fa fa-question-circle fa-2x\"></i></button> -->\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft red\" id=\"remove-option-poll\" aria-label=\"");
      out.print( lang.getContent("button.remove_option") );
      out.write(" 1\"><i class=\"fa fa-trash fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t<li class=\"option-item\" id=\"option-item\">\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-transparent fleft\"><i class=\"fa fa-sort fa-2x\"></i></button> -->\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"circle-info circle-grey fleft\">2</div>\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin:0px;\">\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id='option2' class=\"form-control fleft\" index=\"2\" placeholder=\"");
      out.print( lang.getContent("question.edit.placeholder.option") );
      out.write(" 2\" aria-label=\"");
      out.print( lang.getContent("question.edit.aria_label.option") );
      out.write(" 2\" style=\"width: 100%; !important;\"/>\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<span  id='option2-feedback' class='glyphicon glyphicon-remove form-control-feedback hidden' aria-hidden='true' style=\"color:#A94442;right: 20px;\"></span>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t\t\t\t<span  id='option2-error' class='error hidden' style='top: 0px;right: -180px;'>");
      out.print( lang.getContent("msg.error.poll.option") );
      out.write("</span>\t\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"option-icons fleft\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-transparent fleft\" data-toggle=\"modal\" data-target=\"#importFile\"><i class=\"fa fa-file-image-o fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft\"><i class=\"fa fa-question-circle fa-2x\"></i></button> -->\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft red\" id=\"remove-option-poll\" aria-label=\"");
      out.print( lang.getContent("button.remove_option") );
      out.write(" 2\"><i class=\"fa fa-trash fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t<li class=\"center\" id=\"li-add-option-poll\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm active\" id=\"btn-add-option-poll\" ><i class=\"fa fa-plus-square\"></i><span>");
      out.print( lang.getContent("button.add_option") );
      out.write("</span></button>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\t</ul>\t\t\t\t\t\t\t\t     \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t     \t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t     \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t     \t<fieldset class=\"survey-frame\">\r\n");
      out.write("\t\t\t\t\t\t\t     \t\t<legend>");
      out.print( lang.getContent("poll.new.legend.result") );
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t\t\t     \t\t\r\n");
      out.write("\t\t\t\t\t\t\t     \t\t<div class=\"margin-bottom-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"ackText\" class=\"control-label left\">");
      out.print( lang.getContent("poll.new.label.acknowledgment") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t<textarea class=\"form-control\" id=\"ackText\" rows=\"3\" placeholder=\"");
      out.print( lang.getContent("poll.new.placeholder.acknowledgment") );
      out.write("\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<legend>");
      out.print( lang.getContent("poll.new.legend.call_survey") );
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"results-page-call\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"margin-bottom-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pollCallText\" >");
      out.print( lang.getContent("poll.new.label.call") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t     \t<textarea class=\"form-control\" id=\"pollCallText\" rows=\"3\" placeholder=\"");
      out.print( lang.getContent("poll.new.placeholder.call") );
      out.write("\"></textarea>\t\t\t\t\t\t\t\t\t     \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"margin-bottom-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pollLinkLabel\" >");
      out.print( lang.getContent("poll.new.label.link_label") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t     \t<input type=\"text\" class=\"form-control\" id=\"pollLinkLabel\" name=\"title\" placeholder=\"");
      out.print( lang.getContent("poll.new.placeholder.link_label") );
      out.write("\">\t\t\t\t\t\t\t\t\t     \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"margin-bottom-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pollLinkUrl\" >");
      out.print( lang.getContent("poll.new.label.link_url") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t     \t<input type=\"text\" class=\"form-control\" id=\"pollLinkUrl\" name=\"title\" placeholder=\"");
      out.print( lang.getContent("poll.new.placeholder.link_url") );
      out.write("\">\t\t\t\t\t\t\t\t\t     \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t     \t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t     \t\r\n");
      out.write("\t\t\t\t\t\t\t     \t<div class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t     \t    <input type=\"button\" name=\"createNewPoll\" id=\"btnCreateNewPoll\" class=\"btn btn-primary\" value=\"");
      out.print( lang.getContent("button.create") );
      out.write("\"/> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t    \t\t</div> \r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");

lang.close();

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
