/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2016-10-06 11:27:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.surveyManager.frames;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ilu.surveytool.language.Language;
import ilu.surveytool.constants.Attribute;
import ilu.surveytool.databasemanager.DataObject.Survey;

public final class fNewQuestion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ilu.surveytool.language.Language");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.Survey");
    _jspx_imports_classes.add("ilu.surveytool.constants.Attribute");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Survey survey = (Survey) request.getAttribute(Attribute.s_SURVEY_INFO); 

Language lang = new Language(getServletContext().getRealPath("/")); 
lang.loadLanguage(Language.getLanguageRequest(request));

      out.write("\t\r\n");
      out.write("\t\t\t\t<!-- Modal -->\r\n");
      out.write("\t\t\t\t<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\t\t<div class=\"modal fade survey-win\" id=\"newQuestionModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-dialog survey-win-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t    \t<div class=\"panel panel-primary\"> \r\n");
      out.write("\t\t\t\t    \t\t<div class=\"panel-heading\"> \r\n");
      out.write("\t\t\t\t        \t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"");
      out.print( lang.getContent("button.close") );
      out.write(' ');
      out.print( lang.getContent("question.new.title") );
      out.write("\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("\t\t\t\t    \t\t\t<h2 class=\"panel-title\">");
      out.print( lang.getContent("question.new.title") );
      out.write("</h2> \r\n");
      out.write("\t\t\t\t    \t\t</div> \r\n");
      out.write("\t\t\t\t    \t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t    \t\t\t<fieldset class=\"survey-frame\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t<legend>");
      out.print( lang.getContent("question.new.question_type") );
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"row qtype-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"col-sm-1 center btn-qtype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn-transparent\" id=\"shortText\"><i class=\"fa fa-square-o fa-2x btn btn-default\"></i> <span class=\"qtype-icon-text\">");
      out.print(lang.getContent("question.new.formfield"));
      out.write("</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"col-sm-1 center btn-qtype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn-transparent\" id=\"longText\"><i class=\"fa fa-align-justify fa-2x btn btn-default\"></i> <span class=\"qtype-icon-text\">");
      out.print(lang.getContent("question.new.paragraph"));
      out.write("</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"col-sm-1 center btn-qtype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn-transparent\" id=\"multiple\"><i class=\"fa fa-list fa-2x btn btn-default\"></i> <span class=\"qtype-icon-text\">");
      out.print(lang.getContent("question.new.multiple"));
      out.write("</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"col-sm-1 center btn-qtype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn-transparent\" id=\"simple\"><i class=\"fa fa-list-ul fa-2x btn btn-default\"></i> <span class=\"qtype-icon-text\">");
      out.print(lang.getContent("question.new.simple"));
      out.write("</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <li class=\"col-sm-1 center btn-qtype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn-transparent\" id=\"ordering\"><i class=\"fa fa-sort-numeric-asc fa-2x btn btn-default\"></i> <span class=\"qtype-icon-text\">");
      out.print(lang.getContent("question.new.ordering"));
      out.write("</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <li class=\"col-sm-1 center btn-qtype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn-transparent\" id=\"grading\"><i class=\"fa fa-sort-numeric-asc fa-2x btn btn-default\"></i> <span class=\"qtype-icon-text\">");
      out.print(lang.getContent("question.new.grading"));
      out.write("</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"col-sm-1 center btn-qtype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn-transparent\" id=\"matrix\"><i class=\"fa fa-th fa-2x btn btn-default\"></i> <span class=\"qtype-icon-text\">");
      out.print(lang.getContent("question.new.matrix"));
      out.write("</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"col-sm-1 center btn-qtype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn-transparent\" id=\"scale\"><i class=\"fa fa-th fa-2x btn btn-default\"></i> <span class=\"qtype-icon-text\">");
      out.print(lang.getContent("question.new.scale"));
      out.write("</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!--  <div class=\"col-sm-1 center btn-qtype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a id=\"code\"><i class=\"fa fa-file-code-o fa-2x btn btn-default\"></i> <span class=\"qtype-icon-text\">");
      out.print( lang.getContent("question.new.code"));
      out.write("</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>--> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t    \t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t    \t\t\t<div class=\"survey-frame frame-basic-Settings\" id=\"frame-basic-Settings\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t<h3>");
      out.print( lang.getContent("question.new.basic_settings.title") );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<div class=\"close-frame\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t<button class=\"btn-transparent btn-close-aspa\" id=\"basic-settings-close\" title=\"Close basic settings\" aria-label=\"");
      out.print( lang.getContent("button.close") );
      out.write(' ');
      out.print( lang.getContent("question.new.basic_settings.title") );
      out.write("\"><i class=\"fa fa-times-circle fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t<input type=\"hidden\" id=\"qtypevalue\" name=\"qtype\" value=\"\" />\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t<input type=\"hidden\" id=\"surveyid\" name=\"surveyid\" value=\"");
      out.print( survey.getSurveyId() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin:0px;\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\t\t<label for=\"qstatement\" >");
      out.print( lang.getContent("question.statement") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     \t\t<textarea class=\"form-control\" id=\"qstatement\" rows=\"5\" placeholder=\"");
      out.print( lang.getContent("placeholder.type_here") );
      out.write("\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span  id='qstatement-feedback' class='glyphicon glyphicon-remove form-control-feedback hidden' aria-hidden='true' style='top:30px;right: 20px'></span>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t\t<span id='qstatement-error' class='error hidden' style=''>");
      out.print( lang.getContent("msg.error.qstatement.text") );
      out.write("</span>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-5 basic-settings-right-options\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"div-create-question-mandatory row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"mandatory\" class=\"col-md-5\" ><i class=\"fa fa-asterisk red\"></i><span>");
      out.print( lang.getContent("question.mandatory") );
      out.write("</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control-small col-md-6\" id=\"mandatory\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t<option value=\"false\" selected>");
      out.print( lang.getContent("label.no") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t    <option value=\"true\">");
      out.print( lang.getContent("label.yes") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"div-create-question-optional-answer row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"askAlways\" class=\"col-md-5\" ><i class=\"fa fa-unlock-alt red\"></i><span>");
      out.print( lang.getContent("question.notAnswerRequeried") );
      out.write("</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control-small col-md-6\" id=\"askAlways\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t<option value=\"false\" selected>");
      out.print( lang.getContent("label.no") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t    <option value=\"true\">");
      out.print( lang.getContent("label.yes") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"div-btn-create-question center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"");
      out.print( lang.getContent("button.create") );
      out.write("\" class=\"btn btn-primary\" id=\"create-question\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t    \t\t\t\t</div>\t\t\t\t    \t\t\t\t\r\n");
      out.write("\t\t\t\t    \t\t\t</div>\t\t\t\t    \t\t\t\r\n");
      out.write("\t\t\t\t    \t\t</div> \r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t  \t\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
