/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2016-10-06 11:27:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.surveyManager.frames;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ilu.surveytool.constants.Address;
import ilu.surveytool.language.Language;
import ilu.surveytool.databasemanager.DataObject.LoginResponse;
import ilu.surveytool.constants.Attribute;
import java.util.HashMap;
import java.util.Map;

public final class fNewSurvey_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ilu.surveytool.constants.Address");
    _jspx_imports_classes.add("ilu.surveytool.language.Language");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.LoginResponse");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("ilu.surveytool.constants.Attribute");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Language lang = new Language(getServletContext().getRealPath("/")); 
lang.loadLanguage(Language.getLanguageRequest(request));

HttpSession sessions = request.getSession(false); 
	LoginResponse loginResp = (LoginResponse)sessions.getAttribute(Attribute.s_USER_SESSION_INFO);


      out.write("\r\n");
      out.write("\r\n");
      out.write("\t  \t\t\t<!-- Modal -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"modal fade survey-win\" id=\"newSurveyModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-dialog survey-win-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t    \t<div class=\"panel panel-primary\"> \r\n");
      out.write("\t\t\t\t    \t\t<div class=\"panel-heading\"> \r\n");
      out.write("\t\t\t\t        \t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"");
      out.print( lang.getContent("button.close") );
      out.write(' ');
      out.print( lang.getContent("survey.new.title") );
      out.write("\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("\t\t\t\t    \t\t\t<h2 class=\"panel-title\">");
      out.print( lang.getContent("survey.new.title") );
      out.write("</h2> \r\n");
      out.write("\t\t\t\t    \t\t</div> \r\n");
      out.write("\t\t\t\t    \t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t    \t\t\t\t<form action=\"");
      out.print( Address.s_SERVLET_CREATE_SURVEY_SERVLET );
      out.write("\" method=\"POST\" class=\"form-horizontal\" id=\"formcreatenewsurvey\">\r\n");
      out.write("\t\t\t    \t\t\t\t\t<fieldset class=\"survey-frame\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t<legend>");
      out.print( lang.getContent("survey.new.legend") );
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-7 margin-bottom-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"surveyTitle\" class=\"col-sm-5 control-label left\">");
      out.print( lang.getContent("survey.new.label.survey_title") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   \t<div class=\"form-group\" style=\"margin:0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t <div class=\"col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t     \t\t<input type=\"text\" class=\"form-control\" id=\"surveyTitle\" name=\"title\" placeholder=\"");
      out.print( lang.getContent("placeholder.type_here") );
      out.write("\"  style=\"margin-left: 11px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t     \t\t<span  id='surveyTitle-feedback' class='glyphicon glyphicon-remove form-control-feedback hidden' aria-hidden='true'></span>\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<span id='surveyTitle-error' class='error hidden' style='top: 0px;'>");
      out.print( lang.getContent("msg.error.newsurvey.title") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"surveyProject\" class=\"col-sm-5 control-label left\"> ");
      out.print( lang.getContent("survey.new.label.project") );
      out.write(" </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin:0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   \t\t\t<input type=\"text\" class=\"form-control\" id=\"surveyProject\" name=\"project\" placeholder=\"");
      out.print( lang.getContent("survey.new.placeholder.project") );
      out.write("\"/>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   \t\t\t<span  id='surveyProject-feedback' class='glyphicon glyphicon-remove form-control-feedback hidden' aria-hidden='true'></span>\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<span id='surveyProject-error' class='error hidden' style='top: 0px;'>");
      out.print( lang.getContent("msg.error.newsurvey.project") );
      out.write("</span>\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-12 margin-bottom-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"defaultLanguage\" class=\"col-sm-3 control-label left\">");
      out.print( lang.getContent("survey.new.default.language") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin:0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t     \t\t<select id=\"defaultLanguage\" name=\"defaultLanguage\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    \t");

									                    	for (Map.Entry<String, String> entry : loginResp.getListLanguage().entrySet()) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    \t\t<option value=\"");
      out.print(entry.getKey() );
      out.write('"');
      out.write('>');
      out.print(entry.getValue() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    \t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                   </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-12 margin-bottom-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <label for=\"surveyDescription\" class=\"col-sm-3 control-label left\">");
      out.print( lang.getContent("survey.new.label.short_description") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6 margin-bottom-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<textarea class=\"form-control\" id=\"surveyDescription\" name=\"description\" placeholder=\"");
      out.print( lang.getContent("placeholder.type_here") );
      out.write("\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-3 center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" id=\"createnewsurvey\" class=\"btn btn-primary btn-create-survey\" value=\"");
      out.print( lang.getContent("button.create") );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t    \t\t</div> \r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");

lang.close();

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
