<%@page import="ilu.surveytool.constants.Attribute"%>
<%@page import="ilu.surveytool.language.Language"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%
String footerPath = "jsp/common/masterComponents/footer.jsp";
Language lang = new Language(getServletContext().getRealPath("/")); 
lang.loadLanguage(Language.getLanguageRequest(request));
%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="<%= lang.getCurrentLanguage() %>">
	<head>
		<jsp:include page="jsp/common/masterComponents/head.jsp" />
	</head>
  	<body>
  		<div class="main-container">
  			<div class="page-header">
  				<jsp:include page="jsp/common/masterComponents/header.jsp" />
  			</div>
  			
  			<div class="body-content st-styles">
	  			<div class="survey-free-content content" >
	  			<%if(lang.getCurrentLanguage().equals("es")) { %>
					<h2>Términos del Servicio</h2>
					<p>Bienvenido a ILUNION Survey tool ("SurveyTool"), el sitio web, el API y servicio (colectivamente, el "Servicio") creado por ILUNION Accesibilidad, Estudios y Proyectos S.A.U. ("ILUNION", “nosotros”, “nuestro”). Al acceder o utilizar el Servicio, usted indica que ha leído, comprendido y aceptado estar obligado por estos Términos de Servicio ("Términos") y la Política de Privacidad. Estos términos se aplican a TODOS los visitantes que acceden al Servicio ("Usuarios").</p>
					  			
					<h3>Descripción del servicio</h3>					
					<p>SurveyTool ofrece un servicio de creación y gestión de encuestas y sondeos.</p>

					<h3>Contenido</h3>
					<p>El SurveyTool, por su naturaleza, se compone de dos tipos de contenido. "Contenido estático", que es el contenido que no puede ser modificado por los usuarios y "Contenido dinámico" creado y modificado por los usuarios.</p> 
					<p>El diseño, el Contenido estático y la estructura de la navegación han sido realizados por ILUNION gracias al proyecto Prosperity4all, que recibió financiación del Séptimo Programa Marco de investigación, desarrollo tecnológico y demostración de la Unión Europea con el acuerdo nº 610510.</p>
					<p>La información o las opiniones de este sitio web no representan necesariamente la opinión de la Comisión Europea (CE). El logotipo del 7PM en este sitio web es propiedad de la Comisión Europea. El uso del logo refleja que Prosperity4All planea recibir financiación de la Comisión Europea. Aparte de esto, la Comisión Europea no tiene ninguna responsabilidad por el contenido de esta página web.</p>

					<p><b>Cambio o interrupción del servicio:</b> Podemos, sin previo aviso, cambiar el Servicio; dejar de proporcionar el Servicio o las características del Servicio, a usted o a los usuarios en general; o crear límites de uso para el Servicio. Podemos cancelar o suspender permanentemente o temporalmente su acceso al Servicio sin previo aviso y responsabilidad por cualquier motivo, incluyendo si, a nuestra sola determinación, usted viola cualquier disposición de estos Términos, con o sin causa que lo justifique. En caso de rescisión del Servicio con o sin causa que lo justifique, usted sigue estando vinculado por estos Términos con respecto a cualquier provisión que tenga por objeto perdurar tras la rescisión del Servicio.</p>
					<p><b>Cuenta en SurveyTool.</b> Su cuenta de SurveyTool le da acceso a los servicios y funcionalidades que podemos establecer y actualizar de vez en cuando y a nuestra sola discreción. Podemos mantener diferentes tipos de cuentas para diferentes tipos de usuarios. Si abre una cuenta de SurveyTool en nombre de una empresa, organización u otra entidad, entonces (a) "usted" le incluye a usted y a esa entidad, y (b) representa y garantiza que es un representante autorizado de la entidad con la autoridad para obligar a la entidad cumplir estos Términos y que usted acepta estos Términos en nombre de la entidad. Usted nunca puede usar la cuenta de otro usuario sin permiso. Al crear su cuenta, debe proporcionar información precisa y completa. Usted es el único responsable de la actividad que se produce en su cuenta, y debe mantener la contraseña de su cuenta segura. Le recomendamos que utilice contraseñas "fuertes" (contraseñas que usan una combinación de letras mayúsculas y minúsculas, números y símbolos) con su cuenta. Debe notificar a SurveyTool inmediatamente sobre cualquier incumplimiento de seguridad o uso no autorizado de su cuenta. SurveyTool no será responsable de ninguna pérdida causada por el uso no autorizado de su cuenta. Al proporcionar a SurveyTool su dirección de correo electrónico, usted da su consentimiento a que utilicemos la dirección de correo electrónico para enviarle avisos relacionados con el servicio, incluidos los avisos requeridos por ley, en lugar de comunicación por correo postal. También podemos usar su dirección de correo electrónico para enviarle otros mensajes, como cambios en las características del Servicio y ofertas especiales. Si no desea recibir dichos mensajes de correo electrónico, puede informarnos explícitamente enviando un correo electrónico a iluaepidi@gmail.com. Si rechaza recibir nuestros correos electrónicos, no recibirá mensajes sobre actualizaciones, mejoras u ofertas.</p>
					<p><b>Suscripción.</b> ILUNION ofrece el Servicio que está disponible gratuitamente.</p>
					<p><b>Normas del servicio.</b> Usted acepta no realizar ninguna de las siguientes actividades prohibidas: (i) copiar, distribuir o divulgar cualquier parte del Contenido generado por el usuario en cualquier medio, incluyendo, sin limitación, cualquier "scraping" automatizado o no automatizado, excepto los usos permitidos bajo la sección "API" posterior; (ii) usar cualquier sistema automatizado, incluyendo, sin limitación, "robots", "spiders", "lectores fuera de línea", etc., para acceder al Servicio de manera que envíe más mensajes de solicitud a los servidores de SurveyTool de lo que un ser humano pueda producir razonablemente en el mismo período de tiempo mediante el uso de un navegador web convencional (excepto que SurveyTool otorgue a los operadores de los motores de búsqueda públicos permiso revocable para utilizar spiders para copiar materiales de SurveyTool con el único propósito y únicamente en la medida necesaria para crear públicamente índices disponibles de los materiales, pero no cachés o archivos de dichos materiales); (iii) la transmisión de correo no deseado, cartas en cadena u otro correo electrónico no solicitado; (iv) intentar interferir con, comprometer la integridad o seguridad del sistema o descifrar cualquier transmisión hacia o desde los servidores que ejecutan el Servicio; (v) tomar cualquier acción que imponga o pueda imponer a nuestra sola discreción una carga excesiva o desproporcionadamente grande en nuestra infraestructura; (vi) cargar datos inválidos, virus, gusanos u otros agentes de software a través del Servicio; (vii) recoger o recopilar cualquier información de identificación personal, incluyendo nombres de cuentas del Servicio; (viii) cargar, publicar, transmitir, compartir, almacenar o de otra manera poner a disposición del público en el sitio, u otros canales, cualquier información privada de identificación personal de terceros, incluyendo pero no limitado a: direcciones, números de teléfono, direcciones de correo electrónico, números de Seguridad Social y números de tarjetas de crédito; (ix) usar el Servicio para cualquier propósito de solicitud comercial; (x) suplantar a otra persona o de otra manera falsificar su afiliación con una persona o entidad o realizar fraude; (xi) interferir con el buen funcionamiento del Servicio; (xii) acceder a cualquier contenido del Servicio a través de cualquier tecnología o medio que no sea el proporcionado o autorizado por el Servicio o el permiso escrito de ILUNION; o (xiii) omitiendo las medidas que podamos usar para prevenir o restringir el acceso al Servicio, incluyendo, sin limitación, las características que impiden o restringen el uso o la copia de cualquier contenido o imponen limitaciones al uso del Servicio o al contenido del mismo.</p>
					<p>Está expresamente prohibido acceder al contenido audiovisual disponible en el Servicio para cualquier propósito o de cualquier otra forma que no sea Streaming (como se define más adelante). "Transmisión" significa una transmisión digital contemporánea de una obra audiovisual a través de Internet desde el Servicio SurveyTool hasta el dispositivo de un Usuario de manera que los datos estén destinados a visualización en tiempo real y no estén destinados a ser copiados, almacenados, descargados permanentemente o redistribuido por el Usuario.</p>
					<p>Usted es el único responsable de sus interacciones con otros usuarios de SurveyTool. Nos reservamos el derecho, pero no la obligación, de monitorear el contenido de las encuestas y sondeos para evaluar si este contenido es ofensivo, discriminatorio o viola cualquier ley. ILUNION no tendrá ninguna responsabilidad por sus interacciones con otros Usuarios, ni por la acción o inacción de ningún Usuario.</p>
					
					<h3>Licencia de uso</h3>
					<p>Sujeto a los términos y condiciones de estos Términos, ILUNION le otorga una licencia no exclusiva, limitada, no transferible, libremente revocable para usar el Servicio para su uso personal, no comercial (es decir, no puede usar el Servicio para proporcionar anuncios) y como lo permitan las características del Servicio. ILUNION se reserva todos los derechos no expresamente concedidos aquí en el Servicio y el Contenido de SurveyTool (tal como se define más adelante) . ILUNION se reserva el derecho de cancelar su licencia para usar el Servicio en cualquier momento y por cualquier razón o en el futuro para cobrar por el uso comercial.</p>

					<h3>Licencia de producto</h3>
					<p>Además, SurveyTool se ofrece como un producto (SurveyTool-p) para usuarios y organizaciones que desean ejecutar su propia instancia de SurveyTool-p. El SurveyTool-p está disponible bajo un esquema de licencias doble por el cual el uso de SurveyTool-p en proyectos compatibles con AGPL Versión 3. Consulte la versión 3 de AGPL para obtener más detalles. Sin embargo, si los términos de AGPL Versión 3.0 son incompatibles con su uso de SurveyTool-p, ILUNION Accesibilidad, Estudios y Proyectos dispone de términos de licencia alternativos. Por favor, envíe sus preguntas sobre iluaepidi@gmail.com.</p>
					<p>Si su software es compatible con AGPLv3, puede utilizar SurveyTool-p bajo sus términos de licencia de código abierto sin más consideración. Sin embargo, si su software no está licenciado bajo una licencia compatible con código abierto, como una licencia propietaria, debe ponerse en contacto con ILUNION Accesibilidad, Estudios y Proyectos para acordar términos de licencia alternativos para cubrir su uso de SurveyTool-p. En resumen, si obtiene una ventaja comercial utilizando SurveyTool-p con una solución de código cerrado, debe disponer de una licencia alternativa para su uso de SurveyTool-p que, como mínimo, eliminará la necesidad de publicar su código fuente. En cambio, si desea utilizar SurveyTool-p bajo sus términos de código abierto, debe contribuir a la comunidad el código fuente de la solución que utiliza SurveyTool-p, para que otros puedan beneficiarse de ella en la medida que usted se beneficia de SurveyTool-p. El código fuente debe estar disponible en la web del servicio directamente o mediante un link a un repositorio abierto bajo los términos de licencia AGPLv3</p>
				
					<h3>Responsabilidad del usuario y contenido enviado por el usuario</h3>
					<p>Algunas áreas del Servicio permiten a los Usuarios publicar contenido como los editores de encuestas y sondeos (cualquier material que un Usuario envíe, publica, muestre o de otra manera pone a disposición en el Servicio "Contenido de Usuario").</p>
					<p>Usted acepta no publicar Contenido de Usuario que: (i) pueda crear un riesgo de daño, pérdida, lesión física o mental, angustia emocional, muerte, discapacidad, desfiguración o enfermedad física o mental a usted, a cualquier otra persona o cualquier animal; (ii) puede crear un riesgo de cualquier otra pérdida o daño a cualquier persona o propiedad; (iii) busca dañar o explotar a los niños exponiéndolos a contenido inapropiado, pidiendo detalles de identificación personal o de otra manera; (iv) puede constituir o contribuir a un delito o agravio; (v) contiene cualquier información o contenido que sea ilegal (incluyendo, sin limitación, la divulgación de información privilegiada bajo la ley de valores o de los secretos comerciales de otra parte); o (vi) contiene cualquier información o contenido que usted no tiene el derecho de poner a disposición bajo ninguna ley o bajo relaciones contractuales o fiduciarias. Usted acepta que cualquier Contenido de Usuario que publique no violará los derechos de terceros de ningún tipo, incluyendo, sin limitación, los Derechos de Propiedad Intelectual (como se definen más adelante), los derechos de privacidad o los derechos de publicidad. En la medida en que su Contenido de Usuario contenga música, por la presente usted declara que usted es el propietario de todos los derechos de autor, incluyendo, sin limitación, los derechos de interpretación, mecánicos y grabaciones de sonido, con respecto a cada composición musical. La grabación de sonido contenida en dicho Contenido de Usuario o su uso está cubierta por una excepción de “uso justo” y tiene el poder de conceder la licencia otorgada a continuación. ILUNION se reserva el derecho, pero no está obligado, a rechazar y/o eliminar cualquier Contenido de Usuario que ILUNION crea, a su sola discreción, viola estas disposiciones. Usted entiende que publicar su Contenido de Usuario en el Servicio no es un sustituto para registrarlo con ninguna Oficina de Derechos de Autor en el mundo o cualquier otra organización de derechos.</p>
					<p>Para los propósitos de los Términos, se entiende por "Derechos de Propiedad Intelectual" todos los derechos de patentes, derechos de autor, derechos sobre los esquemas de trazado de circuitos integrados, derechos morales, derechos de publicidad, marcas comerciales, marcas comerciales y marcas de servicio, buena voluntad, secretos comerciales y otros derechos de propiedad intelectual, así como todas las solicitudes y registros, renovaciones y ampliaciones de los mismos, conforme a las leyes de cualquier estado, país, territorio u otra jurisdicción.</p>
					<p>En relación con su Contenido de Usuario, usted afirma, declara y garantiza lo siguiente: Su Contenido de Usuario y el uso de SurveyTool como se contempla en estos Términos y el Servicio no violará ninguna ley ni infringirá ningún derecho de terceros, incluyendo pero no limitado a cualquier derecho de propiedad intelectual, derecho de publicidad y derechos de privacidad.</p>
					<p>ILUNION puede ejercer los derechos sobre su Contenido de Usuario otorgado bajo estos Términos sin responsabilidad sin el pago de ninguna tarifa, remanente, pago, honorario o regalías de gremio pagaderos bajo cualquier acuerdo de negociación colectiva o de otra manera.</p>
					<p>ILUNION no asume ninguna obligación ni responsabilidad por ningún Contenido de Usuario que usted o cualquier otro Usuario o terceros publique o envíe a través del Servicio. Usted será el único responsable de su Contenido de Usuario y las consecuencias de publicarla, y acepta que solo estamos actuando como un canal pasivo para su distribución y publicación en línea de su Contenido de Usuario. Usted entiende y acepta que puede estar expuesto al Contenido de Usuario que es impreciso, inapropiado, inapropiado para los niños, o de otra manera inadecuado para su propósito, y usted acepta que ILUNION no será responsable de los daños y perjuicios que usted alega incurrir como resultado del Usuario Contenido.</p>
					<p>Al publicar cualquier Contenido de Usuario en el Servicio, usted otorga expresamente y declara y garantiza que tiene todos los derechos necesarios para otorgar a ILUNION una licencia mundial, libre de regalías, sublicenciable, transferible, perpetua, irrevocable y no exclusiva para usar reproducir, editar, traducir, distribuir, publicar y hacer obras derivadas de todo el Contenido de Usuario y su nombre, voz y/o semejanza tal y como aparecen en su Contenido de Usuario, en su totalidad o en parte, y en cualquier forma, medio o tecnología, ya sea conocida o desarrollada en el futuro, para uso en relación con el Servicio, incluyendo sin limitación para promover y redistribuir parte o todo el Servicio (y sus obras derivadas) en cualquier formato de medios y por cualquier medio de comunicación. Usted también otorga a cada Usuario del Servicio una licencia no exclusiva para acceder a su Contenido de Usuario a través del Servicio y para usar, reproducir, distribuir, exhibir y llevar a cabo dicho Contenido de Usuario permitido por la funcionalidad del Servicio y bajo estos Términos.</p>
					
					<h3>Responsabilidad del editor y directrices de contenido</h3>
					<p>ILUNION permite un servicio de creación y gestión de encuestas y sondeos, y al hacerlo, la libertad de expresión y de identidad son valores fundamentales del Servicio. Sin embargo, hay una serie de categorías de contenido y comportamiento que ponen en peligro el Servicio al plantear riesgos a usuarios, editores o servicios de terceros que utilizan SurveyTool. Los sitios web o representantes de sitios web que publiquen contenido inapropiado o muestren conductas inapropiadas en relación con su uso del Servicio, incluidas las siguientes categorías, pueden ver suspendida o cancelada su cuenta de SurveyTool: Chantaje o extorsión, derecho de autor o infracción de marcas, recopilación de datos engañosa, daño a menores o animales, suplantación de identidad, intimidación de usuarios del servicio SurveyTool, malware, violaciones de privacidad, spam o actividades ilegales.</p>
					<p>La lista anterior puede modificarse o ampliarse en cualquier momento, y las decisiones de desactivación de cuentas individuales quedan a discreción exclusiva de ILUNION.</p>
				
					<h3>API</h3>
					<p>SurveyTool proporciona acceso a partes de su Servicio a través de un API bajo los mismos términos de licencia (AGPLv3); a los efectos de estas Condiciones, dicho acceso constituye el uso del Servicio. ILUNION le pide que use esta funcionalidad respetuosamente, y como se puede describir en cualquier documentación que proporcionemos. No puede utilizar estas o cualquier otra función del mismo para permitir la visualización de una parte sustancial de la base de datos de SurveyTool o reproducir, duplicar o copiar cualquiera o todos los servicios de SurveyTool. ILUNION se reserva el derecho de cambiar esta funcionalidad en cualquier momento y de deshabilitar el acceso al API en cualquier momento por cualquier motivo o razón.</p>

					<h3>Propiedad y atribución de SurveyTool</h3>
					<p>SurveyTool, el logotipo de SurveyTool y el diseño de SurveyTool son marcas registradas de ILUNION y no pueden ser utilizados sin el permiso expreso por escrito de ILUNION, excepto para la atribución.</p>
					<p>Todas las demás marcas no propiedad de ILUNION que aparecen en este sitio son propiedad de sus respectivos propietarios, que pueden o no estar afiliados, conectados o patrocinados por ILUNION. A excepción de su Contenido de Usuario, el Servicio y todos los materiales incluidos o transferidos por el mismo, incluyendo, sin limitación, software, imágenes, texto, gráficos, ilustraciones, logotipos, API, software, patentes, marcas comerciales, marcas de servicio, videos, música y Contenido de Usuario pertenecientes a otros Usuarios (el "Contenido de SurveyTool"), y todos los Derechos de Propiedad Intelectual relacionados con ellos, son propiedad exclusiva de ILUNION y sus licenciantes (incluidos otros Usuarios que publican Contenido de Usuario al Servicio). Salvo que se indique explícitamente en el presente documento, no se considerará que ninguna de las presentes Condiciones Generales crea una licencia en virtud de dichos Derechos de Propiedad Intelectual y acepta no vender, licenciar, alquilar, modificar, distribuir, copiar, reproducir, publicar, adaptar, editar o crear trabajos derivados de cualquier Contenido de SurveyTool. El uso del Contenido de SurveyTool para cualquier propósito no expresamente permitido por estos Términos está estrictamente prohibido.</p>
					
					<h3>Enlaces de terceros</h3>
					<p>El Servicio puede contener enlaces a sitios web de terceros, anunciantes, servicios, ofertas especiales u otros eventos o actividades que no pertenezcan o sean controlados por ILUNION. ILUNION no respalda ni asume ninguna responsabilidad por dichos sitios, información, materiales, productos o servicios de terceros. Si accede a un sitio web de terceros desde el Servicio, lo hace bajo su propio riesgo y entiende que estos Términos y la Política de privacidad de SurveyTool no se aplican a su uso de dichos sitios. Usted exonera expresamente a ILUNION de toda responsabilidad derivada del uso de cualquier sitio web, servicio o contenido de terceros. Además, los tratos o la participación en las promociones de los anunciantes que se encuentran en el Servicio, incluido el pago y la entrega de mercancías, y cualquier otro término (como las garantías) son exclusivamente entre usted y dichos anunciantes. Usted acepta que ILUNION no será responsable de ninguna pérdida o daño de cualquier tipo relacionado con sus transacciones con dichos anunciantes.</p>
					
					<h3>Indemnización</h3>
					<p>Usted se compromete a defender, indemnizar y eximir a ILUNION y a sus subsidiarias, agentes, licenciantes, gerentes y otras empresas afiliadas, así como a sus empleados, contratistas, agentes, funcionarios y directores, de y contra cualquier reclamación, daño , pasivos, costos o deuda y gastos (incluyendo pero no limitado a los honorarios de abogados) que surjan de: (i) su uso y acceso al Servicio, incluyendo cualquier dato o contenido transmitido o recibido por usted; (ii) la violación de cualquier disposición de estos Términos, incluyendo, sin limitación, el incumplimiento de cualquiera de las declaraciones y garantías anteriores; (iii) su violación de cualquier derecho de terceros, incluyendo, sin limitación, cualquier derecho de privacidad o Derechos de Propiedad Intelectual; (iv) su violación de cualquier ley, regla o regulación aplicable; (v) cualquier reclamación o daños que surjan como resultado de cualquiera de su Contenido de Usuario o cualquiera de los que se envíe a través de su cuenta; o (vi) el acceso y uso de cualquier otra parte del Servicio con su nombre de usuario, contraseña u otro código de seguridad.</p>
					
					<h3>Sin Garantía y Limitación de Responsabilidad</h3>
					<p>El servicio se presta "tal como es" y "según disponibilidad". El uso del servicio es bajo su propio riesgo. Hasta el máximo permitido por la ley aplicable, el servicio se presta sin garantías de ningún tipo, ya sea expresa o implícita, incluyendo, pero no limitado a, garantías implícitas de comerciabilidad, aptitud para un propósito particular o no infracción. Sin limitar lo anterior, ILUNION, sus filiales y sus licenciantes no garantizan que el contenido sea preciso, fiable o correcto; que el servicio cumplirá sus requisitos; que el servicio estará disponible en cualquier momento o lugar en particular, ininterrumpido o seguro; que cualquier defecto o error será corregido; o que el servicio está libre de virus u otros componentes dañinos. Cualquier contenido descargado u obtenido de otra manera a través del uso del servicio se descarga bajo su propio riesgo y usted será el único responsable de cualquier daño a su sistema informático o pérdida de datos que resulte de tal descarga o su uso del servicio.</p>
					<p>ILUNION no garantiza, respalda, garantiza o asume la responsabilidad de ningún producto o servicio anunciado u ofrecido por un tercero a través del servicio de SurveyTool o cualquier sitio web o servicio con hipervínculo y SurveyTool no será parte ni monitoreará de ninguna manera ninguna transacción entre usted y terceros proveedores de productos o servicios. ILUNION, sus afiliados, agentes, directores, empleados, proveedores o licenciatarios no serán responsables de cualquier daño directo, indirecto, punitivo, incidental, especial, consecuente o ejemplar, incluyendo, sin limitación, daños y perjuicios, pérdida de beneficios, fondo de comercio, uso, datos u otras pérdidas intangibles, que resulten del uso o la imposibilidad de utilizar este servicio. Bajo ninguna circunstancia ILUNION será responsable de cualquier daño, pérdida o lesión que resulte de la piratería informática, la manipulación indebida u otro acceso o uso no autorizado del servicio o de su cuenta o la información contenida en el mismo.</p>
					<p>En la medida máxima permitida por la ley aplicable, ILUNION no asume responsabilidad alguna por: (i) errores o inexactitudes de contenido; (ii) lesiones personales o daños a la propiedad, de cualquier naturaleza, que resulten de su acceso o uso de nuestro servicio; (iii) cualquier acceso o uso no autorizado de nuestros servidores seguros y / o cualquier y cualquier información personal almacenada allí; (iv) cualquier interrupción o cese de transmisión hacia o desde el servicio; (v) cualquier error, virus, troyanos, o similares que puedan ser transmitidos a través de nuestro servicio por cualquier tercero; (vi) cualquier error u omisión en cualquier contenido o por cualquier pérdida o daño incurrido como resultado del uso de cualquier contenido publicado, enviado por correo electrónico, transmitido o puesto a disposición de otro modo a través del servicio; y / o (vii) el contenido del usuario o la conducta difamatoria, ofensiva o ilegal de cualquier tercero. En ningún caso ILUNION, sus afiliados, agentes, directores, empleados, proveedores o licenciatarios serán responsables frente a usted por cualquier reclamación, procedimiento, responsabilidad, obligación, daño, pérdida o costo.</p>
					<p>Esta cláusula de limitación de responsabilidad se aplica tanto si la presunta responsabilidad se basa en un contrato, agravio, negligencia, responsabilidad estricta o cualquier otra base, incluso si ILUNION ha sido informada de la posibilidad de tal daño. La limitación de responsabilidad anterior se aplicará en la máxima medida permitida por la ley en la jurisdicción aplicable.</p>
					<p>Algunos estados no permiten la exclusión de garantías implícitas o la exclusión o limitación de daños incidentales o consecuentes, por lo que las limitaciones o exclusiones anteriores pueden no aplicarse a usted. Estos términos le otorgan derechos legales específicos y también puede tener otros derechos que varían de un estado a otro. Las renuncias, exclusiones y limitaciones de responsabilidad bajo estos términos no se aplicarán en la medida en que lo prohíba la ley aplicable.</p>
					<p>El Servicio es controlado y operado desde sus instalaciones en España. ILUNION no hace ninguna representación de que el Servicio es apropiado o está disponible para su uso en otros lugares. Aquellos que accedan o utilizan el Servicio desde otras jurisdicciones lo hacen por su propia voluntad y son totalmente responsables del cumplimiento de todas las leyes y reglamentos aplicables de España y locales.</p>
					
					<h3>Asignación</h3>
					<p>Estos Términos y todos los derechos y licencias otorgados en virtud del presente documento no podrán ser transferidos o asignados por usted, pero ILUNION podrá asignarlos sin restricción alguna. Cualquier intento de transferencia o cesión en violación del presente será nulo y sin efecto.</p>
					
					<h3>Procedimientos de notificación y cambios en los términos</h3>
					<p>ILUNION puede proporcionar notificaciones, ya sea que tales notificaciones sean requeridas por la ley o sean para fines de marketing u otros fines comerciales, a través de un aviso por correo electrónico, un aviso escrito o impreso, o mediante la publicación de dicha notificación en nuestro sitio web. Discreción única. ILUNION se reserva el derecho de determinar la forma y los medios de proporcionar notificaciones a nuestros Usuarios, siempre y cuando usted pueda optar por no recibir determinados medios de notificación como se describe en estos Términos. ILUNION no es responsable de ningún filtrado automático que usted o su proveedor de red pueda aplicar a las notificaciones por correo electrónico que enviamos a la dirección de correo electrónico que nos proporciona. ILUNION puede, a su sola discreción, modificar o actualizar estos Términos de vez en cuando. Cuando cambiamos estos Términos, actualizaremos la fecha de la parte inferior de esta página. El uso continuado del Servicio después de cualquier cambio constituye su aceptación de los nuevos Términos de Servicio. Si no está de acuerdo con estos Términos o con nuestra Política de privacidad, no acceda ni utilice el Servicio. Le recomendamos que revise esta página periódicamente.</p>
					
					<h3>Otros</h3>
					<p><b>Ley que rige.</b> Usted acepta que: (i) el Servicio se considerará únicamente con sede en España; y (ii) el Servicio se considerará pasivo y no dará lugar a jurisdicción personal sobre ILUNION, ya sea específica o general, en jurisdicciones distintas de España. Estos Términos se regirán por las leyes internas sustantivas de España, sin respetar sus principios de conflicto de leyes. Queda expresamente excluida la aplicación de la Convención de las Naciones Unidas sobre los Contratos de Compraventa Internacional de Mercaderías. Usted acepta someterse a la jurisdicción de Madrid, España para cualquier acción por la cual conservemos el derecho de solicitar una medida cautelar u otra reparación equitativa en un tribunal de jurisdicción competente para prevenir la infracción real o amenazada, apropiación indebida o violación de nuestros derechos de autor, marcas comerciales, secretos comerciales, patentes u otros derechos de propiedad intelectual o de propiedad, tal y como se establece en la disposición de Arbitraje siguiente.</p>
					<p><b>General.</b> ILUNION y usted son entidades independientes, y nada en los Términos, o mediante el uso de los Servicios, creará ninguna sociedad, empresa conjunta, agencia, franquicia, representante de ventas o relación laboral entre ILUNION y usted. Estos Términos sustituyen a las Condiciones de Servicio anteriores y representan el acuerdo completo entre ILUNION y usted. Si cualquier disposición de los Términos se considera ilegal o inexigible, no se perjudicará la continuación en toda la fuerza del resto de los Términos y la disposición ilegal o no ejecutable de los Términos será cortada en consecuencia. Ninguna renuncia a cualquier término de estas Condiciones se considerará una renuncia adicional o continua de dicho término o cualquier otro término, y la omisión de ILUNION de hacer valer cualquier derecho o disposición bajo estos Términos no constituirá una renuncia a tal derecho o disposición.</p>
					<p>Estos Términos se publicaron por primera vez y entraron en vigor el 24 de febrero de 2017.</p>
				<% } else { %>
					<h2>Terms of Service</h2>
					<p>Welcome to ILUNION’s Survey tool (“SurveyTool ”), the website, API and service (collectively, the “Service”) by ILUNION Accesibilidad, Estudios y Proyectos S.A.U. (“ILUNION”, “we,” or “us” or “our”). By accessing or using the Service you signify that you have read, understood and agree to be bound by these Terms of Service ("Terms") and the Privacy Policy. These terms apply to ALL visitors who access the Service (“Users”).</p>
					  			
					<h3>Service description</h3>					
					<p>The SurveyTool offers a survey and poll creation and management service.</p>

					<h3>Content</h3>
					<p>The SurveyTool, by its nature is composed of two content types. “Static content” which is the content that cannot be modified by Users, and “Dynamic content” that is created and can be modified by Users.</p>
					<p>The design, static content and structure of navigation have been made by ILUNION thanks to the Prosperity4all project, which received funding from the Seventh Framework Program for research, technological development and demonstration of the European Union under agreement No 610510.</p>
					<p>The information or opinions on this website does not necessarily represent the view of the European Commission (EC). FP7 logo in this website is owned by the European Commission. The use of the logo reflects that Prosperity4All plans to receive funding from the European Commission. Apart from this, the European Commission has no responsibility for the content of this webpage.</p>
					<p><b>Changing or discontinuing the service:</b> We may, without prior notice, change the Service; stop providing the Service or features of the Service, to you or to users generally; or create usage limits for the Service. We may permanently or temporarily terminate or suspend your access to the Service without notice and liability for any reason, including if in our sole determination you violate any provision of these Terms, or for any or no reason. Upon termination for any reason or no reason, you continue to be bound by these Terms with respect to any provision which is intended to survive termination.</p>
					<p><b>SurveyTool account.</b> Your SurveyTool account gives you access to the services and functionality that we may establish and maintain from time to time and in our sole discretion. We may maintain different types of accounts for different types of Users. If you open a Survey tool account on behalf of a company, organization, or other entity, then (a) “you” includes you and that entity, and (b) you represent and warrant that you are an authorized representative of the entity with the authority to bind the entity to these Terms, and that you agree to these Terms on the entity’s behalf. You may never use another User’s account without permission. When creating your account, you must provide accurate and complete information. You are solely responsible for the activity that occurs on your account, and you must keep your account password secure. We encourage you to use “strong” passwords (passwords that use a combination of upper and lower case letters, numbers and symbols) with your account. You must notify SurveyTool immediately of any breach of security or unauthorized use of your account. SurveyTool will not be liable for any losses caused by any unauthorized use of your account. By providing SurveyTool your email address, you consent to our using the email address to send you Service-related notices, including any notices required by law, in lieu of communication by postal mail. We may also use your email address to send you other messages, such as changes to features of the Service and special offers. If you do not want to receive such email messages, you may inform us explicitly by sending an email to iluaepidi@gmail.com. If you reject to receive our emails you will not receive messages regarding updates, improvements, or offers.</p> 
					<p><b>Subscription.</b>  ILUNION offers the Service that is available to you free of charge.</p>
					<p><b>Service Rules.</b> You agree not to engage in any of the following prohibited activities: (i) copying, distributing, or disclosing any part of the User generated content in any medium, including without limitation by any automated or non-automated “scraping” except for uses allowed under the “Feed and API” section below; (ii) using any automated system, including without limitation “robots,” “spiders,” “offline readers,” etc., to access the Service in a manner that  sends more request messages to the SurveyTool servers than a human can reasonably produce in the same period of time by using a conventional on-line web browser (except that SurveyTool grants the operators of public search engines revocable permission to use spiders to copy materials from the SurveyTool for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials); (iii) transmitting spam, chain letters, or other unsolicited email; (iv) attempting to interfere with, to compromise the system integrity or security or to decipher any transmissions to or from the servers running the Service; (v) taking any action that imposes, or may impose at our sole discretion an unreasonable or disproportionately large load on our infrastructure; (vi) uploading invalid data, viruses, worms, or other software agents through the Service; (vii) collecting or harvesting any personally identifiable information, including account names, from the Service; (viii) uploading, posting, transmitting, sharing, storing or otherwise making publicly available on the site, or other channels, any private, personally identifiable information of any third party, including, but not limited to: addresses, phone numbers, email addresses, Social Security numbers and credit card numbers; (ix) using the Service for any commercial solicitation purposes; (x) impersonating another person or otherwise misrepresenting your affiliation with a person or entity or conducting fraud; (xi) interfering with the proper working of the Service; (xii) accessing any content on the Service through any technology or means other than those provided or authorized by the Service or ILUNION’s written permission; or (xiii) bypassing the measures we may use to prevent or restrict access to the Service, including without limitation features that prevent or restrict use or copying of any content or enforce limitations on use of the Service or the content therein.</p>
 					<p>Accessing the audiovisual content available on the Service for any purpose or in any manner other than Streaming (as defined below) is expressly prohibited. “Streaming” means a contemporaneous digital transmission of an audiovisual work via the Internet from the SurveyTool Service to a User’s device in such a manner that the data is intended for real-time viewing and not intended to be copied, stored, permanently downloaded, or redistributed by the User.</p>
					<p>You are solely responsible for your interactions with other SurveyTool Users. We reserve the right, but have no obligation, to monitor the content of the surveys and polls in order to evaluate if this content is offensive, discriminatory or violates any law. ILUNION shall have no liability for your interactions with other Users, or for any User’s action or inaction.</p>
	
					<h3>Usage License</h3>
					<p>Subject to the terms and conditions of these Terms, ILUNION grants you a non-exclusive, limited, non-transferable, freely revocable license to use the Service for your personal, noncommercial (i.e. you may not use the Service to provide ads) use only and as permitted by the features of the Service. ILUNION reserves all rights not expressly granted herein in the Service and the SurveyTool Content (as defined below). ILUNION reserves the right to terminate your license to use the Service at any time and for any reason or in the future to charge for commercial usage. </p>

					<h3>Product licence</h3>
					<p>Additionally, SurveyTool is offered as a product  (SurveyTool-p) for Users and organizations that want to run their own instance of the SurveyTool-p. The SurveyTool-p is available under a dual licensing scheme whereby use of SurveyTool-p in projects that are licensed so as to be compatible with AGPL Version 3 may use SurveyTool-p under the terms of the compatible license. Please see AGPL Version 3 for more details. However, if AGPL Version 3.0 terms are incompatible with your use of SurveyTool-p, alternative license terms are available from ILUNION Accesibilidad, Estudios y Proyectos -- please direct inquiries about SurveyTool-p licensing to iluaepidi@gmail.com.</p>
					<p>If your software is compatible with AGPL Version 3 you can use SurveyTool-p under its open source license terms without further consideration. However, if your software is not licensed under an open source compatible license, such as a proprietary license, then you should contact ILUNION Accesibilidad, Estudios y Proyectos in order to arrange alternative license terms to cover your use of SurveyTool-p. In short, if you derive a commercial advantage by using SurveyTool-p with a closed source solution, you must arrange alternative license terms for your use of SurveyTool-p which will, at a minimum, remove the need to publish your source code. If you wish to use SurveyTool-p under its free software terms, you must contribute back to the community the source code for the solution you use SurveyTool-p with, so that others may benefit from it as you benefit from SurveyTool-p. The source code must be available from the web of the Service directly, or through a link to an open repository under terms of AGPLv3.</p>
				
					<h3>User Responsibility and User-Posted Content</h3>
					<p>Some areas of the Service allow Users to post content such as the survey and poll editors (any such materials a User submits, posts, displays, or otherwise makes available on the Service “User Content”).</p>
					<p>You agree not to post User Content that: (i) may create a risk of harm, loss, physical or mental injury, emotional distress, death, disability, disfigurement, or physical or mental illness to you, to any other person, or to any animal; (ii) may create a risk of any other loss or damage to any person or property; (iii) seeks to harm or exploit children by exposing them to inappropriate content, asking for personally identifiable details or otherwise; (iv) may constitute or contribute to a crime or tort; (v) contains any information or content that is illegal (including, without limitation, the disclosure of insider information under securities law or of another party’s trade secrets); or (vi) contains any information or content that you do not have a right to make available under any law or under contractual or fiduciary relationships. You agree that any User Content that you post does not and will not violate third-party rights of any kind, including without limitation any Intellectual Property Rights (as defined below), rights of privacy or publicity rights. To the extent that your User Content contains music, you hereby represent that you are the owner of all the copyright rights, including without limitation the performance, mechanical, and sound recordings rights, with respect to each and every musical composition (including lyrics) and sound recording contained in such User Content or your use is covered by a fair use exception and have the power to grant the license granted below. ILUNION reserves the right, but is not obligated, to reject and/or remove any User Content that ILUNION believes, in its sole discretion, violates these provisions. You understand that publishing your User Content on the Service is not a substitute for registering it with any Copyright Office in the world or any other rights organization.</p>
					<p>For the purposes of the Terms, “Intellectual Property Rights” means all patent rights, copyright rights, mask work rights, moral rights, rights of publicity, trademark, trade dress and service mark rights, goodwill, trade secret rights and other intellectual property rights as may now exist or hereafter come into existence, and all applications therefore and registrations, renewals and extensions thereof, under the laws of any state, country, territory or other jurisdiction.</p>
					<p>In connection with your User Content, you affirm, represent and warrant the following: Your User Content and SurveyTool’s use thereof as contemplated by these Terms and the Service will not violate any law or infringe any rights of any third party, including but not limited to any Intellectual Property Rights, right of publicity and privacy rights.</p>
					<p>ILUNION may exercise the rights to your User Content granted under these Terms without liability for payment of any guild fees, residuals, payments, fees, or royalties payable under any collective bargaining agreement or otherwise.</p>
					<p>ILUNION takes no responsibility and assumes no liability for any User Content that you or any other User or third party posts or sends over the Service. You shall be solely responsible for your User Content and the consequences of posting or publishing it, and you agree that we are only acting as a passive conduit for your online distribution and publication of your User Content. You understand and agree that you may be exposed to User Content that is inaccurate, objectionable, inappropriate for children, or otherwise unsuited to your purpose, and you agree that ILUNION shall not be liable for any damages you allege to incur as a result of User Content.</p>
					<p>By posting any User Content on the Service, you expressly grant, and you represent and warrant that you have all rights necessary to grant, to ILUNION a royalty-free, sublicensable, transferable, perpetual, irrevocable, non-exclusive, worldwide license to use, reproduce, modify, publish, list information regarding, edit, translate, distribute, syndicate, publicly perform, publicly display, and make derivative works of all such User Content and your name, voice, and/or likeness as contained in your User Content, in whole or in part, and in any form, media or technology, whether now known or hereafter developed, for use in connection with the Service, including without limitation for promoting and redistributing part or all of the Service (and derivative works thereof) in any media formats and through any media channels. You also hereby grant each User of the Service a non-exclusive license to access your User Content through the Service, and to use, reproduce, distribute, display and perform such User Content as permitted through the functionality of the Service and under these Terms.</p>
					
					<h3>Publisher Responsibility and Content Guidelines</h3>
					<p>ILUNION enables a survey and poll creation and management service, and in doing so, freedom of expression and identity are core values of the Service. There are a number of categories of content and behavior, however, that jeopardize the Service by posing risk to users, publishers or third party services utilizing the SurveyTool. Websites or website representatives publishing inappropriate content or exhibiting inappropriate behaviors in connection with their use of the Service, including from the following categories, may have their SurveyTool account suspended or terminated:</p>
					<ul class="normal-list">
						<li>Blackmail or extortion</li>
						<li>Copyright or trademark Infringement</li>
						<li>Deceitful data collection</li>
						<li>Harm to minors or animals</li>
						<li>Impersonation</li>
						<li>Intimidation of users of the SurveyTool Service</li>
						<li>Malware</li>
						<li>Privacy violations</li>
						<li>Spam</li>
						<li>Unlawful activities </li>
					</ul>
					<p>The above list may be modified or expanded at any time, and individual account deactivation decisions remain at the sole discretion of ILUNION.</p>
				
					<h3>API</h3>
					<p>SurveyTool provides access to portions of its Service via an API under the same license terms (AGPLv3); for the purposes of these Terms, such access constitutes use of the Service. ILUNION asks that you use these features respectfully, and as may be outlined in any documentation that we provide. You may not use these or any other features of the Service itself to allow the display of a substantial portion of the SurveyTool database or reproduce, duplicate or copy any or all of the SurveyTool Service. ILUNION reserves the right to change these features at any time and to disable access to the API at any time for any reason or no reason.</p>

					<h3>SurveyTool Property and Attribution</h3>
					<p>SurveyTool, the SurveyTool logo and the SurveyTool design are trademarks  or trade dress of ILUNION, and may not be used without express written permission from ILUNION, other than for attribution. All other trademarks not owned by ILUNION that appear on this Site are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by ILUNION. Except for your User Content, the Service and all materials therein or transferred thereby, including, without limitation, software, images, text, graphics, illustrations, logos, APIs, software, patents, trademarks, service marks, copyrights, photographs, audio, videos, music, and User Content belonging to other Users (the “SurveyTool Content”), and all Intellectual Property Rights related thereto, are the exclusive  property of ILUNION and its licensors (including other Users who post User Content to the Service). Except as explicitly provided herein, nothing in these Terms shall be deemed to create a license in or under any such Intellectual Property Rights, and you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works from any SurveyTool Content. Use of the SurveyTool Content for any purpose not expressly permitted by these Terms is strictly prohibited.</p>
					
					<h3>Third-Party Links</h3>
					<p>The Service may contain links to third-party websites, advertisers, services, special offers, or other events or activities that are not owned or controlled by ILUNION. ILUNION does not endorse or assume any responsibility for any such third-party sites, information, materials, products, or services. If you access a third party website from the Service, you do so at your own risk, and you understand that these Terms and SurveyTool’s Privacy Policy do not apply to your use of such sites. You expressly relieve ILUNION from any and all liability arising from your use of any third-party website, service, or content. Additionally, your dealings with or participation in promotions of advertisers found on the Service, including payment and delivery of goods, and any other terms (such as warranties) are solely between you and such advertisers. You agree that ILUNION shall not be responsible for any loss or damage of any sort relating to your dealings with such advertisers.</p>
					
					<h3>Indemnity</h3>
					<p>You agree to defend, indemnify and hold harmless ILUNION and its subsidiaries, agents, licensors, managers, and other affiliated companies, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from: (i) your use of and access to the Service, including any data or content transmitted or received by you; (ii) your violation of any provision of these Terms, including without limitation your breach of any of the representations and warranties above; (iii) your violation of any third-party right, including without limitation any right of privacy or Intellectual Property Rights; (iv) your violation of any applicable law, rule or regulation; (v) any claim or damages that arise as a result of any of your User Content or any that is submitted via your account; or (vi) any other party’s access and use of the Service with your unique username, password or other appropriate security code.</p>
					
					<h3>No Warranty and Limitation of Liability</h3>
					<p>The service is provided on an “as is” and “as available” basis. Use of the service is at your own risk. To the maximum extent permitted by applicable law, the service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, or non-infringement. Without limiting the foregoing, ILUNION, its subsidiaries, and its licensors do not warrant that the content is accurate, reliable or correct; that the service will meet your requirements; that the service will be available at any particular time or location, uninterrupted or secure; that any defects or errors will be corrected; or that the service is free of viruses or other harmful components. Any content downloaded or otherwise obtained through the use of the service is downloaded at your own risk and you will be solely responsible for any damage to your computer system or loss of data that results from such download or your use of the service.</p>
					<p>ILUNION does not warrant, endorse, guarantee, or assume responsibility for any product or service advertised or offered by a third party through the SurveyTool service or any hyperlinked website or service, and SurveyTool will not be a party to or in any way monitor any transaction between you and third-party providers of products or services. To the maximum extent permitted by applicable law, in no event shall ILUNION, its affiliates, agents, directors, employees, suppliers or licensors be liable for any direct, indirect, punitive, incidental, special, consequential or exemplary damages, including without limitation damages for loss of profits, goodwill, use, data or other intangible losses, that result from the use of, or inability to use, this service. Under no circumstances will ILUNION be responsible for any damage, loss or injury resulting from hacking, tampering or other unauthorized access or use of the service or your account or the information contained therein.</p>
					<p>To the maximum extent permitted by applicable law, ILUNION assumes no liability or responsibility for any (i) errors, mistakes, or inaccuracies of content; (ii) personal injury or property damage, of any nature whatsoever, resulting from your access to or use of our service; (iii) any unauthorized access to or use of our secure servers and/or any and all personal information stored therein; (iv) any interruption or cessation of transmission to or from the service; (v) any bugs, viruses, trojan horses, or the like that may be transmitted to or through our service by any third party; (vi) any errors or omissions in any content or for any loss or damage incurred as a result of the use of any content posted, emailed, transmitted, or otherwise made available through the service; and/or (vii) user content or the defamatory, offensive, or illegal conduct of any third party. In no event shall ILUNION, its affiliates, agents, directors, employees, suppliers, or licensors be liable to you for any claims, proceedings, liabilities, obligations, damages, losses or costs in an amount.</p>
					<p>This limitation of liability section applies whether the alleged liability is based on contract, tort, negligence, strict liability, or any other basis, even if ILUNION has been advised of the possibility of such damage. The foregoing limitation of liability shall apply to the fullest extent permitted by law in the applicable jurisdiction.</p>
					<p>Some states do not allow the exclusion of implied warranties or the exclusion or limitation of incidental or consequential damages, so the above limitations or exclusions may not apply to you. These terms give you specific legal rights, and you may also have other rights which vary from state to state. The disclaimers, exclusions, and limitations of liability under these terms will not apply to the extent prohibited by applicable law.</p>
					<p>The Service is controlled and operated from its facilities in Spain. ILUNION makes no  representations that the Service is appropriate or available for use in other locations. Those who access or use the Service from other jurisdictions do so at their own volition and are entirely responsible for compliance with all applicable Spain and local laws and regulations.</p>
					
					<h3>Assignment</h3>
					<p>These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by ILUNION without restriction. Any attempted transfer or assignment in violation hereof shall be null and void. </p>
					
					<h3>Notification Procedures and Changes to Terms</h3>
					<p>ILUNION may provide notifications, whether such notifications are required by law or are for marketing or other business related purposes, to you via email notice, written or hard copy notice, or through posting of such notice on our website, as determined by ILUNION in our sole discretion. ILUNION reserves the right to determine the form and means of providing notifications to our Users, provided that you may opt out of certain means of notification as described in these Terms. ILUNION is not responsible for any automatic  filtering you or your network provider may apply to email notifications we send to the email address you provide us. ILUNION may, in its sole discretion, modify or update these Terms from time to time. When we change these Terms, we will update the date at the bottom of this page. Your continued use of the Service after any such change constitutes your acceptance of the new Terms of Service. If you do not agree to these Terms or to our Privacy Policy, please do not access or use the Service. We recommend that you review this page periodically.</p>
					
					<h3>Other</h3>
					<p>Governing Law. You agree that: (i) the Service shall be deemed solely based in Spain; and (ii) the Service shall be deemed a passive one that does not give rise to personal jurisdiction over ILUNION, either specific or general, in jurisdictions other than Spain. These Terms shall be governed by the internal substantive laws of Spain, without respect to its conflict of laws principles. The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. You agree to submit to the personal jurisdiction of Madrid, Spain for any actions for which we retain the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a our copyrights, trademarks, trade secrets, patents, or other intellectual property or proprietary rights, as set forth in the Arbitration provision below.</p>
					<p>General. ILUNION and you are independent entities, and nothing in the Terms, or via use of the Services, will create any partnership, joint venture, agency, franchise, sales representative, or employment relationship between ILUNION and you. These Terms supersede any previous Terms of Service and represent the entire agreement between ILUNION and you.  If any provision of the Terms is adjudged to be illegal or unenforceable, the continuation in full force of the remainder of the Terms will not be prejudiced, and the illegal or unenforceable provision of the Terms shall be severed accordingly. No waiver of any term of these Terms shall be deemed a further or continuing waiver of such term or any other term, and ILUNION’S failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision.</p>
					<p>These Terms were first published and made effective on February 24th, 2017.</p>
					<p>Last modified: 24/02/2016</p>
				<% } %>									
				</div>
	  		</div>
	  		
	  		<footer class="footer">
	  			<jsp:include page="<%= footerPath %>" />
	  		</footer>	
 		</div> 
  	</body>
</html>
				
<%
lang.close();
%>