/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2016-10-07 08:55:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.surveyManager.editQuestions.eqResponses;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ilu.surveytool.databasemanager.constants.DBConstants;
import ilu.surveytool.databasemanager.DataObject.Option;
import ilu.surveytool.databasemanager.DataObject.OptionsGroup;
import ilu.surveytool.constants.Attribute;
import ilu.surveytool.databasemanager.DataObject.Question;
import ilu.surveytool.language.Language;

public final class eqSimple_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.Option");
    _jspx_imports_classes.add("ilu.surveytool.language.Language");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.constants.DBConstants");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.OptionsGroup");
    _jspx_imports_classes.add("ilu.surveytool.constants.Attribute");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.Question");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

											Language lang = new Language(getServletContext().getRealPath("/")); 
											lang.loadLanguage(Language.getLanguageRequest(request));
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taccesibilityTextOption = \"");
      out.print( lang.getContent("accesibility.question.option") );
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tphOption = \"");
      out.print( lang.getContent("question.edit.placeholder.option") );
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

											Question question = (Question) request.getAttribute(Attribute.s_QUESTION);
										
							  				if(question.getOptionsGroups().size() > 0)
							  				{
							  					for(OptionsGroup optionsGroup : question.getOptionsGroups())
							  					{
							  					
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t<ul class=\"option-list\" id=\"option-list\" ogid=\"");
      out.print( optionsGroup.getId() );
      out.write("\" otype=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t");

							  						for(Option option : optionsGroup.getOptions())
							  						{
							  							int index = option.getIndex();
							  							String text = "";
							  							if(option!=null && option.getContents()!=null && option.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_TITLE)!=null){
							  								text = option.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_TITLE).getText();
							  							}
							  							
							  						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t<li class=\"option-item\" id=\"option-item\">\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-transparent fleft\"><i class=\"fa fa-sort fa-2x\"></i></button> -->\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"circle-info circle-grey fleft\">");
      out.print( index );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<label for=\"option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.option") );
      out.write(' ');
      out.write(' ');
      out.print( index );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<input id=\"option\" type=\"text\" maxlength=\"10000\" class=\"option-title form-control fleft\" index=\"");
      out.print( index );
      out.write("\" oid=\"");
      out.print( option.getId() );
      out.write("\" placeholder=\"");
      out.print( lang.getContent("question.edit.placeholder.option") );
      out.write(' ');
      out.print( index );
      out.write("\" value=\"");
      out.print( text );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"option-icons fleft\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-transparent fleft\" data-toggle=\"modal\" data-target=\"#importFile\"><i class=\"fa fa-file-image-o fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft\"><i class=\"fa fa-question-circle fa-2x\"></i></button> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");
 if((boolean)request.getAttribute(Attribute.s_ADD_QUESTIONS)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<label for=\"add-file-option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.addfile.option") );
      out.write(' ');
      out.print( index );
      out.write("</label>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft\" id=\"add-file-option\"  active=\"false\" ><i class=\"fa fa-file-image-o fa-2x\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<label for=\"remove-option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.remove.option") );
      out.write(' ');
      out.print( index );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft red\" id=\"remove-option\" aria-label=\"");
      out.print( lang.getContent("button.remove_option") );
      out.write(':');
      out.write(' ');
      out.print( text );
      out.write("\"><i class=\"fa fa-trash fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t");

								  							request.setAttribute(Attribute.s_OPTION, option);
															
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../eqComponents/eqFilesOptions.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t");

							  						}
							  						
							  						int size = optionsGroup.getOptions().size();
							  						if(size < 2)
							  						{
							  							for(int i = size; i < 2; i++)
							  							{
							  								int index = i + 1;
							  						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t<li class=\"option-item\" id=\"option-item\">\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-transparent fleft\"><i class=\"fa fa-sort fa-2x\"></i></button> -->\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"circle-info circle-grey fleft\">");
      out.print( index );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<label for=\"option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.option") );
      out.write(' ');
      out.write(' ');
      out.print( index );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<input id=\"option\" type=\"text\" maxlength=\"10000\" class=\"option-title form-control fleft\" index=\"");
      out.print( index );
      out.write("\" oid=\"0\" placeholder=\"");
      out.print( lang.getContent("question.edit.placeholder.option") );
      out.write(' ');
      out.print( index );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"option-icons fleft\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-transparent fleft\" data-toggle=\"modal\" data-target=\"#importFile\"><i class=\"fa fa-file-image-o fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft\"><i class=\"fa fa-question-circle fa-2x\"></i></button> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");
 if((boolean)request.getAttribute(Attribute.s_ADD_QUESTIONS)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<label for=\"add-file-option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.addfile.option") );
      out.write(' ');
      out.print( index );
      out.write("</label>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft\" id=\"add-file-option\"  active=\"false\" ><i class=\"fa fa-file-image-o fa-2x\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<label for=\"remove-option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.remove.option") );
      out.write(' ');
      out.write(' ');
      out.print( index );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft red\" id=\"remove-option\" aria-label=\"");
      out.print( lang.getContent("button.remove_option") );
      out.write(' ');
      out.print( index );
      out.write("\"><i class=\"fa fa-trash fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t");

								  							request.setAttribute(Attribute.s_OPTION, optionsGroup.getOptions().get(index));
															
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../eqComponents/eqFilesOptions.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t");

							  							}
							  						}
							  						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t<li class=\"center\" id=\"li-add-option");
      out.print( question.getQuestionId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t");
 if((boolean)request.getAttribute(Attribute.s_ADD_QUESTIONS)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"btn-add-option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.add.option") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm active\" id=\"btn-add-option\"><i class=\"fa fa-plus-square\"></i><span>");
      out.print( lang.getContent("button.add_option") );
      out.write("</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t");

							  					}
							  				}
							  				else
							  				{
							  					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t<ul class=\"option-list\" id=\"option-list\" ogid=\"0\" otype=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t<li class=\"option-item\" id=\"option-item\">\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-transparent fleft\"><i class=\"fa fa-sort fa-2x\"></i></button> -->\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"circle-info circle-grey fleft\">1</div>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<label for=\"option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.option") );
      out.write("  1</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<input id=\"option\" type=\"text\" maxlength=\"10000\" class=\"option-title form-control fleft\" index=\"1\" oid=\"0\" placeholder=\"");
      out.print( lang.getContent("question.edit.placeholder.option") );
      out.write(" 1\" />\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"option-icons fleft\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-transparent fleft\" data-toggle=\"modal\" data-target=\"#importFile\"><i class=\"fa fa-file-image-o fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft\"><i class=\"fa fa-question-circle fa-2x\"></i></button> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");
 
							  									boolean addQuestion = (boolean)request.getAttribute(Attribute.s_ADD_QUESTIONS);
							  									if(addQuestion){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<label for=\"add-file-option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.addfile.option") );
      out.write(" 1</label>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft\" id=\"add-file-option\"  active=\"false\" ><i class=\"fa fa-file-image-o fa-2x\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<label for=\"remove-option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.remove.option") );
      out.write("  1</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft red\" id=\"remove-option\" aria-label=\"r");
      out.print( lang.getContent("button.remove_option") );
      out.write(" 1\"><i class=\"fa fa-trash fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<div class=\"row margin-top-40 hidden\" type=\"global\" id=\"multimediaFrame\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"div_files\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"question-files-frame hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>");
      out.print( lang.getContent("question.edit.files.option.title") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"multimedia-list\" id=\"multimediaFilesList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t<li class=\"option-item\" id=\"option-item\">\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-transparent fleft\"><i class=\"fa fa-sort fa-2x\"></i></button> -->\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"circle-info circle-grey fleft\">2</div>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<label for=\"option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.option") );
      out.write("  2</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<input id=\"option\" type=\"text\" maxlength=\"10000\" class=\"option-title form-control fleft\" index=\"2\" oid=\"0\" placeholder=\"");
      out.print( lang.getContent("question.edit.placeholder.option") );
      out.write(" 2\"/>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<div class=\"option-icons fleft\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-transparent fleft\" data-toggle=\"modal\" data-target=\"#importFile\"><i class=\"fa fa-file-image-o fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft\"><i class=\"fa fa-question-circle fa-2x\"></i></button> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");
 if((boolean)request.getAttribute(Attribute.s_ADD_QUESTIONS)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<label for=\"add-file-option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.addfile.option") );
      out.write(" 2</label>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft\" id=\"add-file-option\"  active=\"false\" ><i class=\"fa fa-file-image-o fa-2x\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<label for=\"remove-option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.remove.option") );
      out.write("  2</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<button class=\"btn btn-transparent fleft red\" id=\"remove-option\" aria-label=\"");
      out.print( lang.getContent("button.remove_option") );
      out.write(" 2\"><i class=\"fa fa-trash fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<div class=\"row margin-top-40 hidden\" type=\"global\" id=\"multimediaFrame\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"div_files\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"question-files-frame hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>");
      out.print( lang.getContent("question.edit.files.option.title") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"multimedia-list\" id=\"multimediaFilesList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t<li class=\"center\" id=\"li-add-option");
      out.print( question.getQuestionId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t");
 
							  								addQuestion = (boolean)request.getAttribute(Attribute.s_ADD_QUESTIONS);
							  								if(addQuestion){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<label for=\"btn-add-option\" class=\"visuallyhidden\">");
      out.print( lang.getContent("accesibility.question.add.option") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm active\" id=\"btn-add-option\" ><i class=\"fa fa-plus-square\"></i><span>");
      out.print( lang.getContent("button.add_option") );
      out.write("</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t\t");

							  				}
							  				
							  			lang.close();							  				
							  			
      out.write("\t\t\t\t\t\t\t  \t\t\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
