/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2016-10-06 11:27:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.surveyManager.components;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ilu.surveytool.databasemanager.DataObject.PollTableInfo;
import ilu.surveytool.constants.Parameter;
import ilu.surveytool.constants.Address;
import ilu.surveytool.constants.Attribute;
import java.util.List;
import ilu.surveytool.language.Language;

public final class cPollsTableList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.PollTableInfo");
    _jspx_imports_classes.add("ilu.surveytool.constants.Address");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ilu.surveytool.constants.Parameter");
    _jspx_imports_classes.add("ilu.surveytool.language.Language");
    _jspx_imports_classes.add("ilu.surveytool.constants.Attribute");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Language lang = new Language(getServletContext().getRealPath("/")); 
lang.loadLanguage(Language.getLanguageRequest(request));

      out.write("\r\n");
      out.write("    \t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t\t");

			  					List<PollTableInfo> polls = (List<PollTableInfo>) request.getAttribute(Attribute.s_POLLS);
			  					if(polls != null && !polls.isEmpty())
			  					{
			  					
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t\t\t<div class=\"surveys-table\" id=\"poll-table\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t<table class=\"table table-bordered\" sumary=\"List of surveys where ...\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t<caption>");
      out.print( lang.getContent("survey_manager.polls.table.caption") );
      out.write("</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"poll-table-tr-th-deadline center\">");
      out.print( lang.getContent("survey_manager.polls.table.column.deadline") );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"center\">");
      out.print( lang.getContent("survey_manager.polls.table.column.poll") );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"poll-table-tr-th-responses center\">");
      out.print( lang.getContent("survey_manager.polls.table.column.url") );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"poll-table-tr-th-numresp center\">");
      out.print( lang.getContent("survey_manager.polls.table.column.num_responses") );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"poll-table-tr-th-actions center\">");
      out.print( lang.getContent("survey_manager.polls.table.column.actions") );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										System.out.println("Servlet: " + Address.s_SERVLET_SURVEYS_SERVLET);
										for(PollTableInfo poll : polls)
										{
											request.setAttribute(Attribute.s_POLL_INFO, poll);
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "cPollRow.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										}
										
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t  \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t\t");

				  					//if(surveys.size() > 5)
				  					if(false)
				  					{
				  						int index = 1;
			  					
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t\t\t<!-- <div class=\"btn-pag center\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <a href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li><a href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <a href=\"#\" aria-label=\"Next\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  \t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t\t");

			  						}
			  					}
			  					else
			  					{
			  					
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t\t<div id=\"no-polls-msg\"><p>");
      out.print( lang.getContent("survey_manager.polls.msg.no_polls") );
      out.write("</p></div>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t\t");

			  					}
			  					
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t\t\r\n");

lang.close();

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
