/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2016-10-06 11:27:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.surveyManager.components;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ilu.surveytool.constants.Parameter;
import ilu.surveytool.constants.Address;
import ilu.surveytool.constants.Attribute;
import ilu.surveytool.databasemanager.DataObject.SurveyTableInfo;
import java.util.List;
import ilu.surveytool.language.Language;

public final class cSurveysList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ilu.surveytool.constants.Address");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ilu.surveytool.constants.Parameter");
    _jspx_imports_classes.add("ilu.surveytool.language.Language");
    _jspx_imports_classes.add("ilu.surveytool.constants.Attribute");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.SurveyTableInfo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Language lang = new Language(getServletContext().getRealPath("/")); 
lang.loadLanguage(Language.getLanguageRequest(request));

      out.write("    \t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"surveys-list\" style=\"margin-bottom: 20px;\">\t    \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<h3>");
      out.print( lang.getContent("survey_manager.surveys.title") );
      out.write("</h3>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( lang.getContent("survey_manager.surveys.description") );
      out.write("\r\n");
      out.write("\t\t  \t\t\t\t\t<div class=\"user-panel-surveys\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t\t\t<div class=\"surveys-create-button\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#newSurveyModal\">");
      out.print( lang.getContent("button.create_new") );
      out.write("</button>\r\n");
      out.write("\t\t  \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t\t\t");

			  					List<SurveyTableInfo> surveys = (List<SurveyTableInfo>) request.getAttribute(Attribute.s_SURVEYS);
			  					if(!surveys.isEmpty())
			  					{
			  					
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t\t\t<!-- <div class=\"row\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t<div class=\"dataTables_length\" id=\"surveys-table_length\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t<label>Show <select name=\"surveys-table_length\" aria-controls=\"surveys-table\" class=\"form-control input-sm\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t\t<option value=\"10\" selected>10</option>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t\t<option value=\"25\">25</option>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t\t<option value=\"50\">50</option>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t\t<option value=\"100\">100</option>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t\t</select> entries</label>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t<div id=\"surveys-table_filter\" class=\"dataTables_filter\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t<label>Search: <input type=\"search\" id=\"table-search\" class=\"form-control input-sm\" placeholder=\"\" aria-controls=\"surveys-table\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t<i class='fa fa-search' aria-hidden='true'></i></label>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t\t<div class=\"surveys-table\">\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t<table class=\"table table-bordered\" sumary=\"List of surveys where ...\" id=\"surveys-table\"  data-page-length='25'>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t<caption>");
      out.print( lang.getContent("survey_manager.surveys.table.caption") );
      out.write("</caption>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"info\" id=\"titles\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"center\">");
      out.print( lang.getContent("survey_manager.surveys.table.column.deadline") );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"center\">");
      out.print( lang.getContent("survey_manager.surveys.table.column.survey") );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"center\">");
      out.print( lang.getContent("survey_manager.surveys.table.column.num_responses") );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"center\">");
      out.print( lang.getContent("survey_manager.surveys.table.column.actions") );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										System.out.println("Servlet: " + Address.s_SERVLET_SURVEYS_SERVLET);
										for(SurveyTableInfo survey : surveys)
										{
											String deadLine = "";
											if(survey.getDeadLineDate() != null) 
											{
												deadLine = survey.getDeadLineDate().toString();
											}
											else
											{
												deadLine =  lang.getContent("survey_manager.table.content.none");
											}
											
											String downloadServiceUrl = "http://" + request.getServerName() + ":" + request.getServerPort() + "/SurveyTool/api/SurveyService/export/" + survey.getSurveyId();
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr id=\"resultdevice\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\">");
      out.print( deadLine );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"");
      out.print( Address.s_SERVLET_SURVEYS_SERVLET + "?" + Parameter.s_SURVEY_ID + "=" + survey.getSurveyId() );
      out.write('"');
      out.write('>');
      out.print( survey.getTitle() );
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( survey.getNumUsers() );
      out.write(' ');
      out.print( lang.getContent("survey_manager.surveys.table.survey_responses") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"progress percent-bar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

													float percentage = 0;
													if(survey.getNumUsers() > 0)
													{
														percentage = ((survey.getNumUsersFinished() * 100) / survey.getNumUsers());	
													}
													
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"");
      out.print( survey.getNumUsersFinished() );
      out.write("\" aria-valuemin=\"0\" aria-valuemax=\"");
      out.print( survey.getNumUsers() );
      out.write("\" style=\"width: ");
      out.print(percentage);
      out.write("%;\">");
      out.print( survey.getNumUsersFinished() );
      out.write('/');
      out.print( survey.getNumUsers() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <li class=\"col-sm-3 center\"><a href=\"#\" title=\"clone survey\"><i class=\"fa fa-clone fa-2x\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t<li class=\"col-sm-2 center\"><a href=\"#\" title=\"statistics\"><i class=\"fa fa-bar-chart fa-2x\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t<li class=\"col-sm-2 center\"><a href=\"#\" title=\"settings\"><i class=\"fa fa-cogs fa-2x\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t<li class=\"col-sm-2 center\"><a href=\"#\" title=\"download\"><i class=\"fa fa-download fa-2x\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t<li class=\"col-sm-3 center\"><a href=\"#\" title=\"pause survey\"><i class=\"fa fa-pause-circle-o fa-2x\"></i></a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t<li class=\"col-sm-3 center\"><i class=\"fa fa-clone fa-2x\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t<li class=\"col-sm-2 center\"><a href=\"SurveyStatisticServlet?surveyid=");
      out.print(survey.getSurveyId());
      out.write("\" aria-label=\"");
      out.print( lang.getContent("survey.edit.tab.go_statistics") );
      out.write("\" title=\"");
      out.print( lang.getContent("survey.edit.tab.go_statistics") );
      out.write("\"><i class=\"fa fa-bar-chart fa-2x\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t<li class=\"col-sm-2 center\"><i class=\"fa fa-cogs fa-2x\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t<li class=\"col-sm-2 center\"><a href=\"");
      out.print( downloadServiceUrl );
      out.write("\" title=\"download\"><i class=\"fa fa-download fa-2x\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t\t\t<li class=\"col-sm-3 center\"><i class=\"fa fa-pause-circle-o fa-2x\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t  \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t\t");

				  					//if(surveys.size() > 5)
				  					if(false)
				  					{
				  						int index = 1;
			  					
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t\t\t<div class=\"btn-pag center\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <a href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li><a href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <a href=\"#\" aria-label=\"Next\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t\t");

			  						}
			  					}
			  					else
			  					{
			  					
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t\t<div><p>");
      out.print( lang.getContent("survey_manager.surveys.msg.no_surveys") );
      out.write("</p></div>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t\t");

			  					}
			  					
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t\t</div>\r\n");

lang.close();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script> \r\n");
      out.write(" \r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("    \tvar table = $('#surveys-table').dataTable({\r\n");
      out.write("    \t\t\"aLengthMenu\": [[10, 25, 50, -1], [10, 25, 50, \"All\"]],\r\n");
      out.write("        \t\"pagingType\": \"full_numbers\",\r\n");
      out.write("            \"scrollCollapse\": false,\r\n");
      out.write("            \"searching\": true,\r\n");
      out.write("            \"ordering\": false,\r\n");
      out.write("            \"bLengthChange\" : true,\r\n");
      out.write("            \"language\": {\r\n");
      out.write("            \t\"url\": \"js/dataTables.");
      out.print(Language.getLanguageRequest(request));
      out.write(".lang\"\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("        });        \r\n");
      out.write("        \r\n");
      out.write("    \ttable.on('draw.dt', function () {\r\n");
      out.write("    \t\t//$('[name=\"surveys-table_length\"]').val(\"10\");\r\n");
      out.write("    \t \t$('#surveys-table_filter label').append(\"<i class='fa fa-search' aria-hidden='true'></i>\");\r\n");
      out.write("        });\r\n");
      out.write("       \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("</script> \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
