/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2016-10-06 11:27:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.surveyManager.bodyPages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ilu.surveytool.language.Language;
import ilu.surveytool.constants.Address;
import ilu.surveytool.databasemanager.DataObject.Question;
import java.util.List;
import ilu.surveytool.databasemanager.constants.DBConstants;
import ilu.surveytool.constants.Attribute;
import java.util.HashMap;
import ilu.surveytool.databasemanager.DataObject.LoginResponse;
import java.util.Map;
import ilu.surveytool.databasemanager.DataObject.Survey;

public final class bEditSurveyQuestions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ilu.surveytool.constants.Address");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ilu.surveytool.language.Language");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.Survey");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.constants.DBConstants");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.LoginResponse");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("ilu.surveytool.databasemanager.DataObject.Question");
    _jspx_imports_classes.add("ilu.surveytool.constants.Attribute");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\tsurveyTree = ");
      out.print( request.getAttribute(Attribute.s_JSON_PAGES) );
      out.write(";\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t");

				Survey survey = (Survey) request.getAttribute(Attribute.s_SURVEY_INFO);
				Survey surveyDefaultLanguage = (Survey) request.getAttribute(Attribute.s_SURVEY_INFO_DEFAULT_LANGUAGE);
				int pageId = (int) request.getAttribute(Attribute.s_PAGE_ID);
				String description = "";
				String descriptionplaceholder="";
				if(survey!=null && survey.getContents()!=null && survey.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_DESCRIPTION)!=null && !survey.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_DESCRIPTION).getText().equals("")){
					description = survey.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_DESCRIPTION).getText();
				}else if(surveyDefaultLanguage!=null && surveyDefaultLanguage.getContents()!=null && surveyDefaultLanguage.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_DESCRIPTION)!=null && !surveyDefaultLanguage.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_DESCRIPTION).getText().equals("")){
					description = surveyDefaultLanguage.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_DESCRIPTION).getText();
				}
				
				String title = "";
				String titleplaceholder = "";
				if(survey!=null && survey.getContents()!=null && survey.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_TITLE)!=null && !survey.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_TITLE).getText().equals("")){
					title = survey.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_TITLE).getText();
				}else if(surveyDefaultLanguage!=null && surveyDefaultLanguage.getContents()!=null && surveyDefaultLanguage.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_TITLE)!=null){
					title = surveyDefaultLanguage.getContents().get(DBConstants.s_VALUE_CONTENTTYPE_NAME_TITLE).getText();
				}
				
				Language lang = new Language(getServletContext().getRealPath("/")); 
				lang.loadLanguage(Language.getLanguageRequest(request));
				
				HttpSession sessions = request.getSession(false); 
  				LoginResponse loginResp = (LoginResponse)sessions.getAttribute(Attribute.s_USER_SESSION_INFO);
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t<div id=\"questions\">\r\n");
      out.write("\t  \t\t\t\t\t<div class=\"browser-left\">Hello</div>\t  \t\t\t\t\t\t  \t\t\r\n");
      out.write("\t  \t\t\t\t\t<div class=\"edit-content-center\">\r\n");
      out.write("\t  \t\t\t\t\t\t<div class=\"edit-survey-head\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t<div class=\"survey-preview\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<button class=\"btn btn-primary\" id=\"survey-preview_btn\">");
      out.print( lang.getContent("button.survey_preview") );
      out.write("</button>\r\n");
      out.write("\t\t  \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t\t\t<div class=\"survey-language\" id=\"survey-language\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<form class=\"\" id=\"survey-language-form\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t\t<label for=\"survey-language-version\" class=\"\" ><i class=\"fa fa-language fa-2x\"></i><span>");
      out.print( lang.getContent("survey.edit.label.lang_version") );
      out.write("</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select class=\"form-control-small\" id=\"survey-language-version\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

					                    	for (Map.Entry<String, String> entry : loginResp.getListLanguage().entrySet()) {
					                    		if(entry.getKey().equals(surveyDefaultLanguage.getDefaultLanguage())){
						                    	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t                    \t\t<option value=\"");
      out.print(entry.getKey() );
      out.write('"');
      out.write('>');
      out.print(entry.getValue() );
      out.write(' ');
      out.write('(');
      out.print(lang.getContent("survey_manager.surveys.default"));
      out.write(")</option>\r\n");
      out.write("\t\t\t\t\t\t                    \t");

						                    	} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t                    \t\t<option value=\"");
      out.print(entry.getKey() );
      out.write('"');
      out.write('>');
      out.print(entry.getValue() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t                    \t\t\r\n");
      out.write("\t\t\t\t\t\t                    \t");

						                    	}
					                    	}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t  \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t  \t\t\t\t\t</div>\r\n");
      out.write("\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t\tif(window.location.href.indexOf(\"langsurvey\") > -1) {\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t$(\"#survey-language-version\").val(window.location.href.substring(window.location.href.indexOf(\"langsurvey=\")+11));\r\n");
      out.write("\t\t\t  \t\t\t\t\t}else{\r\n");
      out.write("\t\t\t  \t\t\t\t    \t$(\"#survey-language-version\").val('");
      out.print(survey.getDefaultLanguage() );
      out.write("');\r\n");
      out.write("\t\t\t  \t\t\t\t    }\r\n");
      out.write("\t\t\t            \t\t\r\n");
      out.write("\t\t\t            \t\t\r\n");
      out.write("\t\t\t            \t\t$('#survey-preview_btn').click(function(publicid){\r\n");
      out.write("\t\t\t            \t\t\t\r\n");
      out.write("\t\t\t            \t\t\tlangselect = $('#survey-language-version').val();\r\n");
      out.write("\t\t\t            \t\t\twindow.open('http://");
      out.print(request.getServerName() );
      out.write(':');
      out.print( request.getServerPort() );
      out.write("/SurveyTool/surveyajs?sid=");
      out.print(survey.getPublicId());
      out.write("&langsurvey='+langselect,'_blank');\r\n");
      out.write("\t\t\t            \t\t\t\r\n");
      out.write("\t\t\t            \t\t});\r\n");
      out.write("\t\t\t            \t\t\r\n");
      out.write("\t\t\t            \t\t\t$('#survey-language-version').change(function(event) {\r\n");
      out.write("\t\t\t            \t\t\t\t\r\n");
      out.write("\t\t\t            \t\t\t\tvar loc = \"http://");
      out.print(request.getServerName() );
      out.write(':');
      out.print( request.getServerPort() );
      out.write("/SurveyTool/SurveysServlet?surveyid=");
      out.print(survey.getSurveyId());
      out.write("&langsurvey=\"+$(\"#survey-language-version\").val();\r\n");
      out.write("\t\t\t            \t\t\t\t//if(location.href.indexOf(\"&\") !=-1)loc=loc.substring(0,loc.indexOf('&'));\r\n");
      out.write("\t\t\t            \t\t\t\t\r\n");
      out.write("\t\t\t            \t\t\t\t window.location=loc;\r\n");
      out.write("\t\t\t            \t\t\t});\r\n");
      out.write("\t\t\t            \t\t\t\r\n");
      out.write("\t\t\t            \t\t\r\n");
      out.write("\t\t\t            \t</script>\r\n");
      out.write("\t\t\t                \r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t");
 if(request.getAttribute(Attribute.s_ADD_QUESTIONS)!=null && !(boolean)request.getAttribute(Attribute.s_ADD_QUESTIONS)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"no-default-survey-frame\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"no-default-info-title\"><span><b>");
      out.print( lang.getContent("survey_manager.surveys.notice") );
      out.write("</b></span> ");
      out.print( lang.getContent("survey_manager.surveys.no_default_language") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t\t<div class=\"edit-survey-frame survey-info\" id=\"survey-info\" sid=\"");
      out.print( survey.getSurveyId() );
      out.write("\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t<button class=\"display-default-arrow\" id=\"display-survey-settings\" display=\"false\" aria-label=\"");
      out.print( lang.getContent("survey.edit.info.aria_label.display") );
      out.write("\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<i class=\"fa fa-caret-right fa-2x\"></i>\r\n");
      out.write("\t\t  \t\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t  \t\t\t\t\t\t<div class=\"widthTitleSurveyCollapsed\" id=\"survey-div-title\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin:0px;\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t\t<input type=\"text\" class=\"survey-info-title\" id=\"survey-info-title\" aria-label=\"");
      out.print( lang.getContent("survey.edit.info.aria_label.title") );
      out.write("\" value=\"");
      out.print( title );
      out.write("\" placeholder=\"");
      out.print( titleplaceholder );
      out.write("\"/>\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t\t<span  id='survey-info-title-feedback' class='glyphicon glyphicon-remove form-control-feedback hidden' aria-hidden='true'></span>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t<span id='survey-info-title-error' class='error hidden' style='top: 0px'>");
      out.print( lang.getContent("msg.error.newsurvey.title") );
      out.write("</span>\t\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t  \t\t\t\t\t\t<div class=\"survey-info-project\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"surveyProject\" class=\"col-sm-4 control-label\"> ");
      out.print( lang.getContent("survey.edit.info.label.project") );
      out.write(" </label>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t<div class=\"form-group\" style=\"margin:0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t\t<input type=\"text\" class=\"form-control\" id=\"surveyProject\" name=\"project\" value=\"");
      out.print( survey.getProject() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t\t<span  id='surveyProject-feedback' class='glyphicon glyphicon-remove form-control-feedback hidden' aria-hidden='true' style='right: 20px'></span>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t\t\t<span id='surveyProject-error' class='error hidden' style='top: 0px;'>");
      out.print( lang.getContent("msg.error.newsurvey.project") );
      out.write("</span>\t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"survey-info-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"surveyDescription\" class=\"col-sm-3 control-label left\">");
      out.print( lang.getContent("survey.edit.info.label.short_description") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t     \t\t\t<textarea class=\"form-control\" id=\"surveyDescription\" rows=\"2\" placeholder=\"");
      out.print(descriptionplaceholder);
      out.write('"');
      out.write('>');
      out.print( description );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <div class=\"survey-info-url\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"clipboard-text\" class=\"col-sm-3 control-label left\">");
      out.print( lang.getContent("survey.edit.info.label.url") );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t     \t\t\t<input type=\"text\" class=\"form-control\" name=\"clipboard-text\" id=\"clipboard-text\" value=\"http://");
      out.print( request.getServerName() );
      out.write(':');
      out.print( request.getServerPort() );
      out.write("/SurveyTool/survey?sid=");
      out.print( survey.getPublicId() );
      out.write("\" disabled />\r\n");
      out.write("\t\t\t\t\t\t\t     \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t<button class=\"col-sm-1 btn-transparent btn-copy-clipboard\" id=\"target-to-copy\" data-clipboard-target=\"clipboard-text\" title=\"");
      out.print( lang.getContent("survey.edit.info.aria_label.copy") );
      out.write("\" aria-label=\"");
      out.print( lang.getContent("survey.edit.info.aria_label.copy") );
      out.write("\"><i class=\"fa fa-clipboard fa-2x\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t  \t\t\t\t\t</div>\t\r\n");
      out.write("\t\t  \t\t\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../components/cSections.jsp", out, false);
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t  \t\t\t\t</div>\r\n");

lang.close();

      out.write("\r\n");
      out.write("\t  \t\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
