/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2016-10-06 11:27:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.surveyManager.bodyPages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ilu.surveytool.constants.Parameter;
import ilu.surveytool.constants.Address;
import ilu.surveytool.language.Language;

public final class bUserPanelHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ilu.surveytool.constants.Address");
    _jspx_imports_classes.add("ilu.surveytool.constants.Parameter");
    _jspx_imports_classes.add("ilu.surveytool.language.Language");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Language lang = new Language(getServletContext().getRealPath("/")); 
lang.loadLanguage(Language.getLanguageRequest(request));

      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t  \t\t\t\t<div class=\"title-content\">\r\n");
      out.write("\t  \t\t\t\t\t<h2>");
      out.print( lang.getContent("user_panel.title") );
      out.write("</h2>\r\n");
      out.write("\t  \t\t\t\t</div>\r\n");
      out.write("\t  \t\t\t\t\r\n");
      out.write("\t  \t\t\t\t<div class=\"content\">\r\n");
      out.write("\t  \t\t\t\t\t");
      out.print( lang.getContent("user_panel.description") );
      out.write("\r\n");
      out.write("\t  \t\t\t\t\t<div class=\"user-panel-menu\">\r\n");
      out.write("\t\t  \t\t\t\t\t<ul class=\"row row-menu\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t<li class=\"col-md-3 center\"><a href=\"");
      out.print( Address.s_SERVLET_USER_PANEL_HOME + "?" + Parameter.s_UPOPTION + "=" + Address.s_BODY_SURVEYS );
      out.write("\"><i class=\"fa fa-list-alt fa-5x\"></i><div>");
      out.print( lang.getContent("user_panel.link.survey") );
      out.write("</div></a></li>\r\n");
      out.write("\t\t  \t\t\t\t\t\t<li class=\"col-md-3 center\"><i class=\"fa fa-users fa-5x\" aria-label=\"User list disabled\"></i><p>");
      out.print( lang.getContent("user_panel.link.users") );
      out.write("</p></li>\r\n");
      out.write("\t\t  \t\t\t\t\t\t<li class=\"col-md-3 center\"><i class=\"fa fa-area-chart fa-5x\" aria-label=\"Panel statistics disabled\"></i><p>");
      out.print( lang.getContent("user_panel.link.statistics") );
      out.write("</p></li>\r\n");
      out.write("\t\t  \t\t\t\t\t\t<li class=\"col-md-3 center\"><i class=\"fa fa-cogs fa-5x\" aria-label=\"Panel settings disabled\"></i><p>");
      out.print( lang.getContent("user_panel.link.settings") );
      out.write("</p></li>\r\n");
      out.write("\t\t  \t\t\t\t\t\t<!-- <li class=\"col-md-3 center\"><a href=\"#\"><i class=\"fa fa-users fa-5x\"></i><div>User list</div></a></li>\r\n");
      out.write("\t\t  \t\t\t\t\t\t<li class=\"col-md-3 center\"><a href=\"#\"><i class=\"fa fa-area-chart fa-5x\"></i><div>Panel statistics</div></a></li>\r\n");
      out.write("\t\t  \t\t\t\t\t\t<li class=\"col-md-3 center\"><a href=\"#\"><i class=\"fa fa-cogs fa-5x\"></i><div>Panel settings</div></a></li> -->\r\n");
      out.write("\t\t  \t\t\t\t\t</ul>\r\n");
      out.write("\t\t  \t\t\t\t</div>\r\n");
      out.write("\t  \t\t\t\t</div>\r\n");
      out.write("\t  \t\t\t</div>\r\n");

lang.close();

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
